force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

mdapipkg/Scratch/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Collateral_CC__c</fullName>
        <label>Collateral CC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Realestate - Residential</fullName>
                </value>
                <value>
                    <fullName>Realestate - Commercial</fullName>
                </value>
                <value>
                    <fullName>Motor Vehicle</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan_to_ValueCC__c</fullName>
        <label>Loan to ValueCC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityWrapper.cls
/***
 * Ver  Ticket#      Date            Author                 Purpose
 * 1.0  JN1-4045     23/11/2020      Ishwari G.(thinqloud)  Wrapper for Opportunity Object
 * 2.0  JN1 - 4359   12/03/2021      Sunil                  Null Condition check is added
 **/
public with sharing class OpportunityWrapper {
  @AuraEnabled
  public String collateralCC;
  @AuraEnabled
  public Decimal loanToValueCC;
  @AuraEnabled
  public Id accountId;
  @AuraEnabled
  public String preAssessmentDecision;
  @AuraEnabled
  public String finalAssessmentDecision;
  @AuraEnabled
  public String financialAccountName;
  @AuraEnabled
  public String financialAccountNumber;
  @AuraEnabled
  public String financialAccountType;

  public OpportunityWrapper(Opportunity opp) {
    if (opp != null) {
      if (opp.Collateral_CC__c != null) {
        this.collateralCC = opp.Collateral_CC__c;
      }
      if (opp.Loan_to_ValueCC__c != null) {
        this.loanToValueCC = opp.Loan_to_ValueCC__c;
      }
      if (opp.AccountId != null) {
        this.accountId = opp.AccountId;
      }
      if (opp.Pre_Approval_list__c != null) {
        this.preAssessmentDecision = opp.Pre_Approval_list__c;
      }
      if (opp.Final_Assessment_Decision_list__c != null) {
        this.finalAssessmentDecision = opp.Final_Assessment_Decision_list__c;
      }
      if (opp.FinServ__FinancialAccount__r.Name != null) {
        this.financialAccountName = opp.FinServ__FinancialAccount__r.Name;
      }
      if (
        opp.FinServ__FinancialAccount__r.FinServ__FinancialAccountNumber__c !=
        null
      ) {
        this.financialAccountNumber = opp.FinServ__FinancialAccount__r.FinServ__FinancialAccountNumber__c;
      }
      if (opp.FinServ__FinancialAccount__r.Account_Type_List__c != null) {
        this.financialAccountType = opp.FinServ__FinancialAccount__r.Account_Type_List__c;
      }
    }
  }
}