mdapipkg/Scratch/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Highest_Level_of_Education__c</fullName>
        <label>Highest Level of Education attained</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_of_Address__c</fullName>
        <label>Status of Address</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Address_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Years_at_Residence__c</fullName>
        <label>Years at Residence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Credit_History_in_last_24_Months__c</fullName>
        <label>Credit History in last 24 Months</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Delinquency</fullName>
                </value>
                <value>
                    <fullName>1 - 10 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>11 - 30 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>31 - 60 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>61 - 90 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>Over 90 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>No Credit History</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/FinServ__Employment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_of_Business_Working_Capita__c</fullName>
        <description>Self employed persons</description>
        <label>Assessment of Business Working Capita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Adequate</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>Not Adequate</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assessment_of_Business__c</fullName>
        <description>Self employed</description>
        <label>Assessment of Business  Fin Performance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good growth and profit trends for 3 - 4 years</fullName>
                </value>
                <value>
                    <fullName>Good growth and profit trends for up to 2 years</fullName>
                </value>
                <value>
                    <fullName>Inconsistent profit/growth trends</fullName>
                </value>
                <value>
                    <fullName>Inadequate growth and/or profit trends</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assessment_of_Statement__c</fullName>
        <label>Assessment of Business Fin Statement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Supported</fullName>
                </value>
                <value>
                    <fullName>Adequately Supported</fullName>
                </value>
                <value>
                    <fullName>Sound Business Plan, Skill and Professional Competence</fullName>
                </value>
                <value>
                    <fullName>Weak Support or Doubtful</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Employment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Employment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <description>Created to replace the first Employment Status picklist with incorrect values.</description>
        <label>Employment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Contractual</fullName>
                </value>
                <value>
                    <fullName>Unemployed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Industry_Category_IFRS_Self_Employed</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_of_Trade__c</fullName>
        <label>Length of Trade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>More than 5 years</fullName>
                </value>
                <value>
                    <fullName>Between 3-5 years</fullName>
                </value>
                <value>
                    <fullName>Between 1-3 years</fullName>
                </value>
                <value>
                    <fullName>Less than a 1 year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nature_of_Engagement__c</fullName>
        <label>Nature of Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Nature_of_Engagement_Self_Employed</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Professional_Category__c</fullName>
        <label>Professional Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Officer</fullName>
                </value>
                <value>
                    <fullName>Clerical</fullName>
                </value>
                <value>
                    <fullName>Skilled Worker</fullName>
                </value>
                <value>
                    <fullName>Unskilled Worker</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/FinServ__EmploymentStatus__c.field-meta.xml
<CustomField>
    <fullName>FinServ__EmploymentStatus__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>Contractual</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Employed</fullName>
                <isActive>false</isActive>
                <label>Employed</label>
            </value>
            <value>
                <fullName>Home Maker</fullName>
                <isActive>false</isActive>
                <label>Home Maker</label>
            </value>
            <value>
                <fullName>Pensioner</fullName>
                <isActive>false</isActive>
                <label>Pensioner</label>
            </value>
            <value>
                <fullName>Retired</fullName>
                <isActive>false</isActive>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Self-Employed</fullName>
                <isActive>false</isActive>
                <label>Self-Employed</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
            <value>
                <fullName>Unemployed with Income</fullName>
                <isActive>false</isActive>
                <label>Unemployed with Income</label>
            </value>
            <value>
                <fullName>Unemployed without Income</fullName>
                <isActive>false</isActive>
                <label>Unemployed without Income</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__Employment__c/recordTypes/Employed.recordType-meta.xml
<RecordType>
    <fullName>Employed</fullName>
    <active>true</active>
    <label>Employed</label>
</RecordType>

force-app/main/default/objects/FinServ__ReciprocalRole__c/FinServ__ReciprocalRole__c.object-meta.xml
<CustomObject>
    <description
  >Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <label>Reciprocal Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__ReciprocalRole__c/fields/FinServ__InverseRole__c.field-meta.xml
<CustomField>
    <fullName>FinServ__InverseRole__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Inverse Role</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__ReciprocalRole__c/fields/FinServ__RelationshipType__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelationshipType__c</fullName>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Contact Contact Relation</fullName>
            </value>
            <value>
                <fullName>Account Account Relation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapipkg/Scratch/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Collateral_CC__c</fullName>
        <label>Collateral CC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Realestate - Residential</fullName>
                </value>
                <value>
                    <fullName>Realestate - Commercial</fullName>
                </value>
                <value>
                    <fullName>Motor Vehicle</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_LOC__c</fullName>
        <label>Collateral LOC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Realestate - Residential</fullName>
                </value>
                <value>
                    <fullName>Realestate - Commercial</fullName>
                </value>
                <value>
                    <fullName>Motor Vehicle</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Address_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Own</fullName>
    </customValue>
    <customValue>
        <fullName>Own (without mortgage)</fullName>
    </customValue>
    <customValue>
        <fullName>Company</fullName>
    </customValue>
    <customValue>
        <fullName>Family</fullName>
    </customValue>
    <customValue>
        <fullName>Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Address Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Education.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Basic</fullName>
    </customValue>
    <customValue>
        <fullName>Primary</fullName>
    </customValue>
    <customValue>
        <fullName>High School</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher Training Colleges</fullName>
    </customValue>
    <customValue>
        <fullName>Community Colleges</fullName>
    </customValue>
    <customValue>
        <fullName>Other College/Institutions</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Post Graduate</fullName>
    </customValue>
    <masterLabel>Education</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Industry_Category_IFRS_Self_Employed.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Retail trade</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>ICT</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <masterLabel>Industry Category - IFRS (Self-Employed)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Nature_of_Engagement_Self_Employed.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Professional service provider</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational service provider</fullName>
    </customValue>
    <customValue>
        <fullName>Trader</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Nature of Engagement (Self-Employed)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductDetailServiceTest.cls
@IsTest
public with sharing class ProductDetailServiceTest {
    @IsTest
    public static void testAge() {
        List<Opportunity> opList = TestDataFactory.CreateOpportunities(1);
        List<Account> accList = TestDataFactory.CreateBasicAccounts(1,'Test');
        accList[0].Status_of_Address__c = 'Family';
        accList[0].Years_at_Residence__c = 4;
        accList[0].Highest_Level_of_Education__c = 'High School';
        accList[0].PersonBirthdate = date.newInstance(System.Today().year()-22, 2, 11);
        insert accList;
        Util.ExecutionCount = 2;
        /*List<FinServ__ReciprocalRole__c> reciprocalRole = new List<FinServ__ReciprocalRole__c>();
        FinServ__ReciprocalRole__c finServReciprocalRole = new FinServ__ReciprocalRole__c();
        finServReciprocalRole.FinServ__InverseRole__c = '';
        finServReciprocalRole.FinServ__RelationshipType__c = '';
        finServReciprocalRole.Name = 'Political Affiliation';
        finServReciprocalRole.DeveloperName = */
        
        opList[0].accountId = accList[0].id;
        opList[0].Collateral_CC__c = 'Realestate - Residential';
        opList[0].Collateral_LOC__c = 'Realestate - Residential';
        insert opList[0];

        FinServ__Employment__c employeeList = TestDataFactory.CreateEmployment(accList[0].id,'Employeement Test');
        employeeList.Current_Employment__c = true;
        employeeList.FinServ__EmploymentStatus__c = 'Permanent';
        employeeList.Employment_Status__c = 'Contractual';
        employeeList.Industry__c = 'Manufacturing';
        employeeList.Professional_Category__c = 'Clerical';
        employeeList.Assessment_of_Business_Working_Capita__c = 'Negative';
        employeeList.Nature_of_Engagement__c = 'Vocational service provider';
        employeeList.Assessment_of_Business__c = 'Good growth and profit trends for 3 - 4 years';
        employeeList.Assessment_of_Statement__c = '	Strongly Supported';
        employeeList.Length_of_Trade__c = 'Between 3-5 years';
        employeeList.RecordTypeId = '012q00000001gsFAAQ';//Schema.SObjectType.FinServ__Employment__c.getRecordTypeInfosByName().get('Employed').getRecordTypeId();
        insert employeeList;

        Applicant__c applicant = TestDataFactory.CreateApplicant(accList[0].id,opList[0].id);
        applicant.Credit_History_in_last_24_Months__c = '1 - 10 Days Delinquent';
        applicant.Assessment_of_Applicant_Net_Worth__c = 'Reasonable net worth';
        insert applicant;

        List<Loan_Calculator__c> loanCalculator =  TestDataFactory.CreateLoanCalculation(1);
        loanCalculator[0].Ability_to_Service_CC__c = 9;
        loanCalculator[0].Ability_to_Service_LOC__c = 10;
        loanCalculator[0].Repayment_Method_CC__c = 'Salary Deduction';
        loanCalculator[0].Repayment_Method_LOC__c = 'Salary Deduction';
        loanCalculator[0].Opportunity__c = opList[0].id;
        insert loanCalculator[0];

        SubCriteriaOptionWrapper SubCriteriaOptionWrapperObj = ProductDetailService.getSubcriteriaOptions(opList[0].id);
        CreditScoreModelWrapper creditScoreModelWrapperObj = new CreditScoreModelWrapper(SubCriteriaOptionWrapperObj);

    }
}