mdapipkg/Scratch/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FinServ__Countries</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculation_Product__c/Loan_Calculation_Product__c.object-meta.xml
<CustomObject>
    <description
  >Auto, Unsecured, Credit card, and Line of credit products for loan calculation.</description>
    <label>Loan Calculation Product</label>
    <nameField>
        <displayFormat>LCP-{000000}</displayFormat>
        <label>Loan Calculation Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculation Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Interest_Rate_Number__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Number__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_Amount_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_Number__c</fullName>
    <description>Loan Amount for product</description>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_Calculation_Id__c.field-meta.xml
<CustomField>
    <fullName>Loan_Calculation_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan calculation</description>
    <label>Loan Calculation</label>
    <referenceTo>Loan_Calculator__c</referenceTo>
    <relationshipLabel>Loan Calculation Products</relationshipLabel>
    <relationshipName>Loan_Calculation_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapipkg/Scratch/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Details__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Details</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Loan_Calculator__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Product Details</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Loan_Calculator__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/PromissoryNoteController.cls
//Sample Applicant Ids are a15f0000002F8z5AAC 	a15f0000002F9sIAAS
//Sample Opportunities Id 006f000000PhctcAAB  006f000000PhpadAAB
//Sample Account Id 001f000001dJOzdAAG	001f000001dXjJ9AAK
public class PromissoryNoteController {
    //Date of Application
    public date dateOfApplication{get;set;}
    public String dateString{get;set;}
    
    //Application ID
    public String applicationIdString{get;set;}
    public Id applicantId{get;set;}
    
    public Account personAccount {get; set;}
    public Applicant__c applicantObject{get; set;}
    public Opportunity oppObject {get; set;}
    public Loan_Calculation_Product__c loanCalculProductObj {get; set;}
    
    public PromissoryNoteController(){
        //Get applicant id from URL
        applicantId = ApexPages.currentPage().getParameters().get(Constants.ID_STRING);
        
        if(applicantId!=Null){
            //Form the date of application value to display in vf page
            dateOfApplication = date.today();
            dateString = dateOfApplication.format();
            
            //Get applicant objects by using the applicant id from URL
            applicantObject = getApplicant(applicantId);
            
            //Get account objects
            personAccount = getAccount(applicantObject.Account__c);
            
            //Get Loan Amount/Limit Value
            loanCalculProductObj = getLoanCalculationProduct(applicantObject.Opportunity__c);
        }
       // Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename= PromissoryNote'); 
    }
    
    private Applicant__c getApplicant(Id applicantId){
        Applicant__c applicantObjectInstance;
        applicantObjectInstance = [SELECT 	Id, 
                                   			Opportunity__c,
                                   			Account__c,
                                   			CurrencyIsoCode
                                   FROM Applicant__c 
                                   WHERE Id =:applicantId];
        
        if(applicantObjectInstance!=Null){
            return applicantObjectInstance;
        }else{
            return Null;
        }
    }
    
    private Account getAccount(Id accountId) {    
        Account accountObj = [SELECT Name,
                              		Street_1__pc,
                              		Street_2__pc,
                              		Street_3__pc,
                              		City_Town__pc,
                              		Residential_Area_District__pc,
                              		Province_Parish_State__pc,
                              		Post_Office_Zip_Code__pc,
                              		Country__c                              
                              FROM Account
                              WHERE Id = :accountId];
        if (accountObj != null) {
            return accountObj;
        }else{
            return Null;   
        }
    }
    
    private Loan_Calculation_Product__c getLoanCalculationProduct(Id oppId){
        Opportunity OppObj = new Opportunity();
        list<Loan_Calculation_Product__c> loanCalPrdct; 
        Loan_Calculation_Product__c loanCalculationProductObj;
        
        OppObj = [SELECT Id,
                  Product_Details__c
                  FROM Opportunity 
                  WHERE Id =: oppId];
     
        if(OppObj!=Null){
            loanCalPrdct = [SELECT Loan_Amount_Number__c,
                            		Interest_Rate_Number__c
                            FROM Loan_Calculation_Product__c 
                            WHERE Loan_Calculation_Id__c =: OppObj.Product_Details__c];
            
            if(loanCalPrdct != Null){
                if(loanCalPrdct.size()>0){
                    loanCalculationProductObj = loanCalPrdct.get(0);         
                    return loanCalculationProductObj;         
                }
            }
            return Null;
        }    
        return Null;
    }
}