mdapipkg/Scratch/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Highest_Level_of_Education__c</fullName>
        <label>Highest Level of Education attained</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_of_Address__c</fullName>
        <label>Status of Address</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Address_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Years_at_Residence__c</fullName>
        <label>Years at Residence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Address_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Own</fullName>
    </customValue>
    <customValue>
        <fullName>Own (without mortgage)</fullName>
    </customValue>
    <customValue>
        <fullName>Company</fullName>
    </customValue>
    <customValue>
        <fullName>Family</fullName>
    </customValue>
    <customValue>
        <fullName>Rent</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Address Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Education.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Basic</fullName>
    </customValue>
    <customValue>
        <fullName>Primary</fullName>
    </customValue>
    <customValue>
        <fullName>High School</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher Training Colleges</fullName>
    </customValue>
    <customValue>
        <fullName>Community Colleges</fullName>
    </customValue>
    <customValue>
        <fullName>Other College/Institutions</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Post Graduate</fullName>
    </customValue>
    <masterLabel>Education</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountWrapper.cls
public class AccountWrapper {

    @AuraEnabled
    public String statusOfAddress;
    @AuraEnabled
    public Decimal yearsAtResident;
    @AuraEnabled
    public Decimal age;
    @AuraEnabled
    public String highestLevelOfEducation;

    public AccountWrapper(Account accountObj) {
        this.age = accountObj.FinServ__Age__pc;
        this.statusOfAddress = accountObj.Status_of_Address__c;
        this.yearsAtResident = accountObj.Years_at_Residence__c;
        this.highestLevelOfEducation = accountObj.Highest_Level_of_Education__c;
    }
}