mdapipkg/Scratch/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Employment_Type__c</fullName>
        <label>Employment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Employment_Status</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

mdapipkg/Scratch/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Emergency_Contact_First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Emergency Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Emergency Contact Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Method__c</fullName>
        <label>Preferred Contact Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Home Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Business Phone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_time_of_contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferred time of contact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Primary_Employment_Type__c</fullName>
        <label>Primary Employment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Employment_Type</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

mdapipkg/Scratch/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Emergency_Contact_First_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Emergency Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Last_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Emergency Contact Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Address_Street_1__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Employer Address Street 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Address_Street_2__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Employer Address Street 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Address_Street_3__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Employer Address Street 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Area_District__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Employer Area/District</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_City_Town__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Employer City/Town</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_City__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Employer City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer_Country__c</fullName>
        <label>Employer Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FinServ__Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalate_to_Tier2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalate to Tier2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Contact_Made__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Contact Made</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Name_of_Current_Employer__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Name of Current Employer</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Previous_Employer__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Previous Employer Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Method__c</fullName>
        <label>Preferred Contact Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Home Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Business Phone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Date_of_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferred Date of Contact</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preferred_Time_of_Contact__c</fullName>
        <label>Preferred Time of Contact</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Previous_Employer_City_Town__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Previous Employer City/Town</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Employer_City__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Previous Employer City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Employer_Street_2__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Previous Employer Street 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Employer_Street_3__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Previous Employer Street 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Employment_Area_District__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Previous Employment Area/District</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Employment_Type__c</fullName>
        <label>Primary Employment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Employment_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_of_Interest__c</fullName>
        <label>Product of Interest</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Group_of_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_in_Collect_Customers_Information__c</fullName>
        <label>Time in Collect Customer Information</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_in_Contact_Made__c</fullName>
        <label>Time in Contact Made</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_in_Determine_Customer_Need_Goals__c</fullName>
        <label>Time Determine Customer Needs and Goals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_in_Disqualified__c</fullName>
        <label>Time in Disqualified</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_in_Nurturing__c</fullName>
        <label>Time in Nurturing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_in_Open__c</fullName>
        <label>Time in Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_in_Qualified__c</fullName>
        <label>Time in Qualified</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_in_Run_Loan_Scenario__c</fullName>
        <label>Time in Run Loan Scenario</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_in_Working__c</fullName>
        <label>Time in Working</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>role__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapipkg/Scratch/objects/Lead_Related_Person__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Lead Related Person</label>
    <nameField>
        <displayFormat>LRPN-{00000000}</displayFormat>
        <label>Lead Related Person Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Related Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Contact_Made__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Contact Made</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Preferred_Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Contact_Method__c</fullName>
    <label>Preferred Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Home Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Mortgage.recordType-meta.xml
<RecordType>
    <fullName>Mortgage</fullName>
    <active>true</active>
    <businessProcess>Test Mortgage Process</businessProcess>
    <label>Mortgage, IPF, Commercial Auto Loan, Cash Secured Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Savings_Chequing.recordType-meta.xml
<RecordType>
    <fullName>Savings_Chequing</fullName>
    <active>true</active>
    <businessProcess>Savings%2FChequing Processes</businessProcess>
    <label>Savings / Chequing</label>
</RecordType>

force-app/main/default/globalValueSets/Employment_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Permanent</fullName>
    </customValue>
    <customValue>
        <fullName>Contractual</fullName>
    </customValue>
    <customValue>
        <fullName>Unemployed</fullName>
    </customValue>
    <customValue>
        <fullName>Pensioner</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Self Employed</fullName>
        <isActive>false</isActive>
        <label>Self Employed</label>
    </customValue>
    <customValue>
        <fullName>Probation</fullName>
        <isActive>false</isActive>
        <label>Probation</label>
    </customValue>
    <masterLabel>Employment Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Employment_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Employed</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Employed</fullName>
    </customValue>
    <customValue>
        <fullName>Unemployed</fullName>
    </customValue>
    <customValue>
        <fullName>Contracted</fullName>
        <isActive>false</isActive>
        <label>Contracted</label>
    </customValue>
    <masterLabel>Employment Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Group_of_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>JN Bank Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Mortgage Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Deposit Account</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Auto Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Commercial Auto Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Line Of Credit</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Unsecured Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank 12 to 1 Loan (Supersize Loan)</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Cash Secured Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Insurance Premium Financing</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Term Share Loan</fullName>
    </customValue>
    <masterLabel>Product Group of Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestLeadTriggerHandler.cls
@isTest
public class TestLeadTriggerHandler {
  @testSetup
  static void setup() {
    User newUser = TestDataFactory.CreateUser('leadtester@test.com');
    insert newUser;
    List<FinServ__ReciprocalRole__c> roles = new List<FinServ__ReciprocalRole__c>();
    List<String> roleNames = new List<String>{
      'Emergency Contact',
      'Political Affiliation',
      'JN Affiliation'
    };
    for (String roleName : roleNames) {
      roles.add(TestDataFactory.CreateRole(roleName));
    }
    insert roles;
  }

  @isTest
  public static void shouldcrmm_TierTwoTrigger() {
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      //Create an Account
      Account acc = TestDataFactory.CreateBasicAccounts(1, 'Stone')[0];
      insert acc;

      //Create an opportunity to merge with converted lead
      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      //Create new lead record
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      insert leadRecord;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;
      System.assert(tsk != null, 'Task is empty');
      Test.startTest();
      //Create a convert lead
      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      Database.LeadConvertResult lcr = Database.convertLead(lc);
      System.assert(lcr.isSuccess());

      leadRecord.Escalate_to_Tier2__c = true;
      update leadRecord;
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldCheckIfNewConversion() {
    Map<String, Id> recordTypes_lead = Util.getRecordTypeids('Lead');

    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      Account acc = TestDataFactory.CreateBasicAccounts(1, 'lastName')[0];
      insert acc;

      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      leadRecord.Industry = 'ICT';
      leadRecord.Primary_Employment_Type__c = 'Employed';
      leadRecord.RecordTypeId = recordTypes_lead.get('Loan');
      insert leadRecord;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;

      Database.LeadConvert lc = new database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      //lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);
      Test.startTest();
      Database.LeadConvertResult lcr = Database.convertLead(lc);
      System.assert(lcr.isSuccess());

      Test.stopTest();
    }
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenOpen() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      List<Lead> leadRecords = TestDataFactory.CreateLeads(2);
      insert leadRecords;

      leadRecords[0].Status = 'Open';
      leadRecords[0].Time_in_Open__c = 500000;
      leadRecords[1].Status = 'Open';

      update leadRecords;
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenWorking() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      List<Lead> leadRecords = TestDataFactory.CreateLeads(2);
      insert leadRecords;

      leadRecords[0].Status = 'Working';
      leadRecords[0].Time_in_Working__c = 500000;
      leadRecords[1].Status = 'Working';

      update leadRecords;
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenContactMade() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      List<Lead> leadRecords = TestDataFactory.CreateLeads(2);
      insert leadRecords;

      leadRecords[0].Status = 'Contact Made';
      leadRecords[0].Time_in_Contact_Made__c = 500000;
      leadRecords[1].Status = 'Contact Made';

      update leadRecords;
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenDetermineCustomersNeedsGoals() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      List<Lead> leadRecords = TestDataFactory.CreateLeads(2);
      insert leadRecords;

      leadRecords[0].Status = 'Determine Customers needs goals';
      leadRecords[0].Time_in_Determine_Customer_Need_Goals__c = 500000;
      leadRecords[1].Status = 'Determine Customers needs goals';

      update leadRecords;
    }

    Test.stopTest();
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenCollectCustomersInformation() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      List<Lead> leadRecords = TestDataFactory.CreateLeads(2);
      insert leadRecords;

      leadRecords[0].Status = 'Collect Customers Information';
      leadRecords[0].Time_in_Collect_Customers_Information__c = 500000;
      leadRecords[1].Status = 'Collect Customers Information';

      update leadRecords;
    }

    Test.stopTest();
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenRunLoanScenarios() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      List<Lead> leadRecords = TestDataFactory.CreateLeads(2);
      insert leadRecords;

      leadRecords[0].Status = 'Run Loan Scenarios';
      leadRecords[0].Time_in_Run_Loan_Scenario__c = 500000;
      leadRecords[1].Status = 'Run Loan Scenarios';

      update leadRecords;
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenDisqualified() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      List<Lead> leadRecords = TestDataFactory.CreateLeads(2);
      insert leadRecords;

      leadRecords[0].Status = 'Disqualified';
      leadRecords[0].Time_in_Disqualified__c = 500000;
      leadRecords[1].Status = 'Disqualified';

      update leadRecords;
    }

    Test.stopTest();
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenQualified() {
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      Account acc = TestDataFactory.CreateBasicAccounts(1, 'lastName')[0];
      insert acc;

      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      leadRecord.Time_in_Qualified__c = 500000;
      insert leadRecord;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;

      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      Test.startTest();
      Database.LeadConvertResult lcr = Database.convertLead(lc);
      leadRecord.Status = 'Qualified';
      update leadRecord;

      Test.stopTest();
    }
  }

  @isTest
  public static void shouldcrmm_lead_trigger_conversion() {
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      //Create an Account
      Account acc = TestDataFactory.CreateBasicAccounts(1, 'Stone')[0];
      insert acc;

      //Create an opportunity to merge with converted lead
      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      //Create new lead record
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      insert leadRecord;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;
      System.assert(tsk != null, 'Task is empty');
      Test.startTest();
      //Create a convert lead
      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      Database.LeadConvertResult lcr = Database.convertLead(lc);
      System.assert(lcr.isSuccess());
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageZeroWhenQualified() {
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      Account acc = TestDataFactory.CreateBasicAccounts(1, 'lastName')[0];
      insert acc;

      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      insert leadRecord;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;

      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      Test.startTest();
      Database.LeadConvertResult lcr = Database.convertLead(lc);

      leadRecord.Status = 'Qualified';
      update leadRecord;

      Test.stopTest();
    }
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenUnqualified() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      List<Lead> leadRecords = TestDataFactory.CreateLeads(2);
      insert leadRecords;

      leadRecords[0].Status = 'Unqualified';
      leadRecords[0].Time_in_Qualified__c = 500000;
      leadRecords[1].Status = 'Unqualified';

      update leadRecords;
    }

    Test.stopTest();
  }

  @isTest
  public static void shouldCrmm_TimeSpentInStageWhenNurturing() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      List<Lead> leadRecords = TestDataFactory.CreateLeads(2);
      insert leadRecords;

      leadRecords[0].Status = 'Nurturing';
      leadRecords[0].Time_in_Nurturing__c = 500000;
      leadRecords[1].Status = 'Nurturing';

      update leadRecords;
    }

    Test.stopTest();
  }

  @isTest
  public static void shouldEnforceLeadOpportunityRecordType() {
    Map<String, Id> recordTypes_opp = Util.getRecordTypeids('Opportunity');
    Map<String, Id> recordTypes_acc = Util.getRecordTypeids('Account');
    Map<String, Id> recordTypes_lead = Util.getRecordTypeids('Lead');

    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');

    System.runAs(newUser) {
      //Create new lead record
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      leadRecord.Service_of_Interest__c = 'JN Bank Auto Loan';
      leadRecord.RecordTypeId = recordTypes_lead.get('Loan');
      leadRecord.Salutation = 'Mr';
      //leadRecord.Last_Contact_Made__c = System.now();
      insert leadRecord;

      Account acc = TestDataFactory.CreateBasicAccounts(1, 'ln')[0];
      acc.FirstName = 'ABC';
      acc.LastName = 'Company';
      insert acc;

      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.StageName = 'Prospecting';
      //opp.RecordTypeId = recordTypes_opp.get('Mortgage');
      insert opp;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;
      System.assert(tsk != null, 'Task is empty');

      //Create a convert lead
      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      System.debug('convertStatus ' + convertStatus.MasterLabel);
      lc.setConvertedStatus(convertStatus.MasterLabel);

      Test.startTest();

      Database.LeadConvertResult lcr = Database.convertLead(lc);
      System.assert(lcr.isSuccess());
      update leadRecord;
    }

    Test.stopTest();
  }

  @isTest
  public static void shouldleadConversionBasic() {
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      //Create an Account
      Account acc = TestDataFactory.CreateBasicAccounts(1, 'Stone')[0];
      insert acc;

      //Create an opportunity to merge with converted lead
      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      //Create new lead record
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      insert leadRecord;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;
      System.assert(tsk != null, 'Task is empty');
      Test.startTest();
      //Create a convert lead
      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      Database.LeadConvertResult lcr = Database.convertLead(lc);
      System.assert(lcr.isSuccess());

      leadRecord.Status = 'Qualified';
      update leadRecord;

      System.assertEquals(
        'Qualified',
        leadRecord.Status,
        'Lead status do not match'
      );
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldValidateIndustryTypeWhenEmployed() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      //Create new lead record
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      insert leadRecord;

      //Update Primary Employment Field and Industry
      leadRecord.Primary_Employment_Type__c = 'Employed';
      leadRecord.Industry = 'Agriculture';

      try {
        update leadRecord;
      } catch (System.DmlException e) {
        Boolean expectedExceptionThrown = e.getMessage()
            .contains(
              'The selected Industry value does not match the Primary Employment Type (Employed) selected'
            )
          ? true
          : false;
        System.AssertEquals(
          expectedExceptionThrown,
          true,
          'Error message was thrown!'
        );
      }
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldValidateIndustryTypeWhenUnemployed() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      //Create new lead record
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      insert leadRecord;

      //Update Primary Employment Field and Industry
      leadRecord.Primary_Employment_Type__c = 'Unemployed';
      leadRecord.Industry = 'Agriculture';

      try {
        update leadRecord;
      } catch (System.DmlException e) {
        Boolean expectedExceptionThrown = e.getMessage()
            .contains(
              'The selected Industry value does not match the Primary Employment Type (Unemployed) selected'
            )
          ? true
          : false;
        System.AssertEquals(
          expectedExceptionThrown,
          true,
          'Error message was thrown!'
        );
      }
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldValidateIndustryTypeWhenSelfemployed() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      //Create new lead record
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      insert leadRecord;

      //Update Primary Employment Field and Industry
      leadRecord.Primary_Employment_Type__c = 'Self-Employed';
      leadRecord.Industry = 'Technology';

      try {
        update leadRecord;
      } catch (System.DmlException e) {
        Boolean expectedExceptionThrown = e.getMessage()
            .contains(
              'The selected Industry value does not match the Primary Employment Type (Self-Employed) selected'
            )
          ? true
          : false;
        System.AssertEquals(
          expectedExceptionThrown,
          true,
          'Error message was thrown!'
        );
      }

      Test.stopTest();
    }
  }

  @isTest
  public static void shouldCreateEmploymentOnConversion() {
    Account acc = TestDataFactory.CreateBasicAccounts(1, 'lastName')[0];
    insert acc;
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      insert leadRecord;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;

      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      test.startTest();

      Database.LeadConvertResult lcr = Database.convertLead(lc);

      leadRecord.Employer_Address_Street_1__c = 'Harbour Street';
      leadRecord.Employer_Address_Street_2__c = 'Crescent Street';
      leadRecord.Employer_Address_Street_3__c = 'Moon Street';
      leadRecord.Employer_Area_District__c = 'Sun District';
      leadRecord.Employer_City_Town__c = 'Small Town';
      leadRecord.Employer_City__c = 'Spanish City';
      leadRecord.Employer_City__c = 'Spanish City';
      leadRecord.Employer_Country__c = 'Jamaica';
      leadRecord.Previous_Employer_Street_2__c = 'Circular Street';
      leadRecord.Previous_Employer_Street_3__c = 'Sun Street';
      leadRecord.Previous_Employment_Area_District__c = 'Moon District';
      leadRecord.Previous_Employer_City_Town__c = 'Half-Way Tree';
      leadRecord.Previous_Employer_City__c = 'St Andrew';
      leadRecord.Name_of_Current_Employer__c = 'Remario Richards';
      leadRecord.Name_of_Previous_Employer__c = 'John Smalls';
      update leadRecord;

      test.stopTest();
    }
  }

  @isTest
  public static void shouldleadActivityEvent() {
    Test.startTest();
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      leadRecord.Preferred_Time_of_Contact__c = Time.newInstance(0, 1, 3, 0);
      leadRecord.Preferred_Date_of_Contact__c = Date.newInstance(2020, 5, 16);
      leadRecord.Preferred_Contact_Method__c = 'Email';
      insert leadRecord;
    }
    Test.stopTest();
  }

  @isTest
  public static void shouldcreateDateTime() {
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      leadRecord.Preferred_Time_of_Contact__c = Time.newInstance(0, 1, 3, 0);
      leadRecord.Preferred_Date_of_Contact__c = Date.newInstance(2020, 5, 16);
      insert leadRecord;
    }
  }

  @isTest
  public static void shouldContactRelatedPersonsWhenAffiliateIsJNBank() {
    Map<String, Id> recordTypeids = Util.getRecordTypeids('Account');
    Id personAccountId = recordTypeids.get('PersonAccount');

    Account acc = TestDataFactory.CreateBasicAccounts(1, 'lastName')[0];
    insert acc;
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      Account e_acc = new Account();
      e_acc.FirstName = 'Travis';
      e_acc.LastName = 'Allen';
      e_acc.Mobile_Number__pc = TestDataFactory.PHONE;
      e_acc.RecordTypeId = personAccountId;
      insert e_acc;

      //System.assert(e_acc.PersonContactId != null, 'Ooops! this account is not a person');

      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];

      leadRecord.Emergency_Contact_First_Name__c = 'Travis';
      leadRecord.Emergency_Contact_Last_Name__c = 'Allen';
      leadRecord.Emergency_Contact_Personal_Email__c = 'leadtester@test.com';
      leadRecord.Emergency_Contact_Mobile__c = TestDataFactory.PHONE;
      insert leadRecord;

      Lead_Related_Person__c relatedLead = new Lead_Related_Person__c();
      relatedLead.TRN__c = '123456789111';
      relatedLead.TItle__c = 'Mr.';
      relatedLead.Role__c = 'ContactRole';
      relatedLead.Relationship__c = 'Father';
      relatedLead.Mobile_Number__c = TestDataFactory.Phone;
      relatedLead.Middle_Name__c = 'JR';
      relatedLead.Lead_and_Referral__c = leadRecord.Id;
      relatedLead.Last_Name__c = 'Jones';
      relatedLead.JN_Location__c = 'Barbican';
      relatedLead.Home_Phone_Number__c = TestDataFactory.PHONE;
      relatedLead.First_Name__c = 'Tevar';
      relatedLead.Email__c = 'tevar@test.com';
      relatedLead.Business_Number__c = TestDataFactory.PHONE;
      relatedLead.Afilliate_Type__c = 'JN Bank';
      insert relatedLead;

      System.assert(relatedLead != null, 'Ooops the related lead is empty');

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;

      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      test.startTest();

      Database.LeadConvertResult lcr = Database.convertLead(lc);

      test.stopTest();
    }
  }

  @isTest
  public static void shouldContactRelatedPersonsWhenAffiliateIsPolitical() {
    Map<String, Id> recordTypeids = Util.getRecordTypeids('Account');
    Id personAccountId = recordTypeids.get('PersonAccount');
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');
    System.runAs(newUser) {
      Account acc = TestDataFactory.CreateBasicAccounts(1, 'lastName')[0];
      insert acc;

      Account e_acc = new Account();
      e_acc.FirstName = 'Travis';
      e_acc.LastName = 'Allen';
      e_acc.Mobile_Number__pc = TestDataFactory.PHONE;
      e_acc.RecordTypeId = personAccountId;
      insert e_acc;

      //System.assert(e_acc.PersonContactId != null, 'Ooops! this account is not a person');

      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];

      leadRecord.Emergency_Contact_First_Name__c = 'Travis';
      leadRecord.Emergency_Contact_Last_Name__c = 'Allen';
      leadRecord.Emergency_Contact_Personal_Email__c = 'leadtester@test.com';
      leadRecord.Emergency_Contact_Mobile__c = TestDataFactory.PHONE;
      insert leadRecord;

      Lead_Related_Person__c relatedLead = new Lead_Related_Person__c();
      relatedLead.TRN__c = '123456789111';
      relatedLead.TItle__c = 'Mr.';
      relatedLead.Role__c = 'ContactRole';
      relatedLead.Relationship__c = 'Father';
      relatedLead.Mobile_Number__c = TestDataFactory.Phone;
      relatedLead.Middle_Name__c = 'JR';
      relatedLead.Lead_and_Referral__c = leadRecord.Id;
      relatedLead.Last_Name__c = 'Jones';
      relatedLead.JN_Location__c = 'Barbican';
      relatedLead.Home_Phone_Number__c = TestDataFactory.PHONE;
      relatedLead.First_Name__c = 'Tevar';
      relatedLead.Email__c = 'tevar@test.com';
      relatedLead.Business_Number__c = TestDataFactory.PHONE;
      relatedLead.Afilliate_Type__c = 'Political';
      insert relatedLead;

      System.assert(relatedLead != null, 'Ooops the related lead is empty');

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;

      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      test.startTest();

      Database.LeadConvertResult lcr = Database.convertLead(lc);

      test.stopTest();
    }
  }

  @isTest
  public static void shouldContactRelatedPersonsWhenAffiliateIsCreditCardExtension() {
    Map<String, Id> recordTypeids = Util.getRecordTypeids('Account');
    Id personAccountId = recordTypeids.get('PersonAccount');
    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');

    System.runAs(newUser) {
      Account acc = TestDataFactory.CreateBasicAccounts(1, 'lastName')[0];
      insert acc;

      Account e_acc = new Account();
      e_acc.FirstName = 'Travis';
      e_acc.LastName = 'Allen';
      e_acc.Mobile_Number__pc = TestDataFactory.PHONE;
      e_acc.RecordTypeId = personAccountId;
      insert e_acc;

      //System.assert(e_acc.PersonContactId != null, 'Ooops! this account is not a person');

      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.Last_Contact_Made__c = System.now();
      opp.StageName = 'Prospecting';
      insert opp;

      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];

      leadRecord.Emergency_Contact_First_Name__c = 'Travis';
      leadRecord.Emergency_Contact_Last_Name__c = 'Allen';
      leadRecord.Emergency_Contact_Personal_Email__c = 'leadtester@test.com';
      leadRecord.Emergency_Contact_Mobile__c = TestDataFactory.PHONE;
      insert leadRecord;

      Lead_Related_Person__c relatedLead = new Lead_Related_Person__c();
      relatedLead.TRN__c = '123456789111';
      relatedLead.TItle__c = 'Mr.';
      relatedLead.Role__c = 'ContactRole';
      relatedLead.Relationship__c = 'Father';
      relatedLead.Mobile_Number__c = TestDataFactory.Phone;
      relatedLead.Middle_Name__c = 'JR';
      relatedLead.Lead_and_Referral__c = leadRecord.Id;
      relatedLead.Last_Name__c = 'Jones';
      relatedLead.JN_Location__c = 'Barbican';
      relatedLead.Home_Phone_Number__c = TestDataFactory.PHONE;
      relatedLead.First_Name__c = 'Tevar';
      relatedLead.Email__c = 'tevar@test.com';
      relatedLead.Business_Number__c = TestDataFactory.PHONE;
      relatedLead.Afilliate_Type__c = 'Credit Card Extension';
      insert relatedLead;

      System.assert(relatedLead != null, 'Ooops the related lead is empty');

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;

      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      test.startTest();

      Database.LeadConvertResult lcr = Database.convertLead(lc);

      test.stopTest();
    }
  }

  @isTest
  public static void shouldAssignStageUponConversionWhenMortgage() {
    Map<String, Id> recordTypes_opp = Util.getRecordTypeids('Opportunity');
    Map<String, Id> recordTypes_acc = Util.getRecordTypeids('Account');
    Map<String, Id> recordTypes_lead = Util.getRecordTypeids('Lead');

    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');

    System.runAs(newUser) {
      //Create new lead record
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      leadRecord.Service_of_Interest__c = 'JN Bank Mortgage Loan';
      leadRecord.RecordTypeId = recordTypes_lead.get('Mortgage');
      leadRecord.Salutation = 'Mr';
      //leadRecord.Last_Contact_Made__c = System.now();
      insert leadRecord;

      Account acc = TestDataFactory.CreateBasicAccounts(1, 'ln')[0];
      acc.FirstName = 'ABC';
      acc.LastName = 'Company';
      insert acc;

      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.StageName = 'Prospecting';
      opp.RecordTypeId = recordTypes_opp.get('Mortgage');
      opp.Product_Purchased__c = 'Product Purchase Place Holder';
      opp.Product_of_Interest__c = 'JN Bank Mortgage Loan';
      insert opp;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;
      System.assert(tsk != null, 'Task is empty');

      //Create a convert lead
      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      System.debug('convertStatus ' + convertStatus.MasterLabel);
      lc.setConvertedStatus(convertStatus.MasterLabel);

      Test.startTest();

      Database.LeadConvertResult lcr = Database.convertLead(lc);
      System.assert(lcr.isSuccess());
      update leadRecord;
    }

    Test.stopTest();
  }

  @isTest
  public static void shouldAssignStageUponConversionWhenSavingsChequing() {
    Map<String, Id> recordTypes_opp = Util.getRecordTypeids('Opportunity');
    Map<String, Id> recordTypes_acc = Util.getRecordTypeids('Account');
    Map<String, Id> recordTypes_lead = Util.getRecordTypeids('Lead');

    User newUser = [SELECT Id FROM User WHERE UserName = 'leadtester@test.com'];
    System.assert(newUser != null, 'User is empty');

    System.runAs(newUser) {
      //Create new lead record
      Lead leadRecord = TestDataFactory.CreateLeads(1)[0];
      leadRecord.Service_of_Interest__c = 'JN Bank Deposit Account';
      leadRecord.RecordTypeId = recordTypes_lead.get('Savings_Chequing');
      leadRecord.Salutation = 'Mr';
      //leadRecord.Last_Contact_Made__c = System.now();
      insert leadRecord;

      Account acc = TestDataFactory.CreateBasicAccounts(1, 'ln')[0];
      acc.FirstName = 'ABC';
      acc.LastName = 'Company';
      insert acc;

      Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
      opp.AccountId = acc.Id;
      opp.StageName = 'Prospecting';
      opp.RecordTypeId = recordTypes_opp.get('Savings_Chequing');
      opp.Product_of_Interest__c = 'JN Bank Deposit Account';
      opp.Product_Purchased__c = 'JN Way Deposit Account';
      insert opp;

      Task tsk = TestDataFactory.CreateTask(newUser.Id, leadRecord.Id);
      tsk.Result__c = 'Contact Made';
      insert tsk;
      System.assert(tsk != null, 'Task is empty');

      //Create a convert lead
      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(leadRecord.id);
      lc.setOwnerId(newUser.Id);
      lc.setAccountId(acc.Id);
      lc.setOpportunityId(opp.Id);

      LeadStatus convertStatus = [
        SELECT Id, MasterLabel
        FROM LeadStatus
        WHERE IsConverted = TRUE
        LIMIT 1
      ];
      System.debug('convertStatus ' + convertStatus.MasterLabel);
      lc.setConvertedStatus(convertStatus.MasterLabel);

      Test.startTest();

      Database.LeadConvertResult lcr = Database.convertLead(lc);
      System.assert(lcr.isSuccess());
      update leadRecord;
    }
    Test.stopTest();
  }
}