mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assessment_of_Applicant_Net_Worth__c</fullName>
        <label>Assessment of Applicant Net Worth</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Strong net worth</fullName>
                </value>
                <value>
                    <fullName>Reasonable net worth</fullName>
                </value>
                <value>
                    <fullName>Low Net Worth</fullName>
                </value>
                <value>
                    <fullName>New worth not commensurate with age and earning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_History_in_last_24_Months__c</fullName>
        <label>Credit History in last 24 Months</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Delinquency</fullName>
                </value>
                <value>
                    <fullName>1 - 10 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>11 - 30 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>31 - 60 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>61 - 90 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>Over 90 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>No Credit History</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/FinServ__Employment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_of_Business_Working_Capita__c</fullName>
        <description>Self employed persons</description>
        <label>Assessment of Business Working Capita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Adequate</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>Not Adequate</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assessment_of_Business__c</fullName>
        <description>Self employed</description>
        <label>Assessment of Business  Fin Performance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good growth and profit trends for 3 - 4 years</fullName>
                </value>
                <value>
                    <fullName>Good growth and profit trends for up to 2 years</fullName>
                </value>
                <value>
                    <fullName>Inconsistent profit/growth trends</fullName>
                </value>
                <value>
                    <fullName>Inadequate growth and/or profit trends</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assessment_of_Statement__c</fullName>
        <label>Assessment of Business Fin Statement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Supported</fullName>
                </value>
                <value>
                    <fullName>Adequately Supported</fullName>
                </value>
                <value>
                    <fullName>Sound Business Plan, Skill and Professional Competence</fullName>
                </value>
                <value>
                    <fullName>Weak Support or Doubtful</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Employment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Employment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <description>Created to replace the first Employment Status picklist with incorrect values.</description>
        <label>Employment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Contractual</fullName>
                </value>
                <value>
                    <fullName>Unemployed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Industry_Category_IFRS_Self_Employed</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_of_Trade__c</fullName>
        <label>Length of Trade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>More than 5 years</fullName>
                </value>
                <value>
                    <fullName>Between 3-5 years</fullName>
                </value>
                <value>
                    <fullName>Between 1-3 years</fullName>
                </value>
                <value>
                    <fullName>Less than a 1 year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nature_of_Engagement__c</fullName>
        <label>Nature of Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Nature_of_Engagement_Self_Employed</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Professional_Category__c</fullName>
        <label>Professional Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Officer</fullName>
                </value>
                <value>
                    <fullName>Clerical</fullName>
                </value>
                <value>
                    <fullName>Skilled Worker</fullName>
                </value>
                <value>
                    <fullName>Unskilled Worker</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/FinServ__EmploymentStatus__c.field-meta.xml
<CustomField>
    <fullName>FinServ__EmploymentStatus__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>Contractual</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Employed</fullName>
                <isActive>false</isActive>
                <label>Employed</label>
            </value>
            <value>
                <fullName>Home Maker</fullName>
                <isActive>false</isActive>
                <label>Home Maker</label>
            </value>
            <value>
                <fullName>Pensioner</fullName>
                <isActive>false</isActive>
                <label>Pensioner</label>
            </value>
            <value>
                <fullName>Retired</fullName>
                <isActive>false</isActive>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Self-Employed</fullName>
                <isActive>false</isActive>
                <label>Self-Employed</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
            <value>
                <fullName>Unemployed with Income</fullName>
                <isActive>false</isActive>
                <label>Unemployed with Income</label>
            </value>
            <value>
                <fullName>Unemployed without Income</fullName>
                <isActive>false</isActive>
                <label>Unemployed without Income</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__Employment__c/recordTypes/Employed.recordType-meta.xml
<RecordType>
    <fullName>Employed</fullName>
    <active>true</active>
    <label>Employed</label>
</RecordType>

mdapipkg/Scratch/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Collateral_CC__c</fullName>
        <label>Collateral CC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Realestate - Residential</fullName>
                </value>
                <value>
                    <fullName>Realestate - Commercial</fullName>
                </value>
                <value>
                    <fullName>Motor Vehicle</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_LOC__c</fullName>
        <label>Collateral LOC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Realestate - Residential</fullName>
                </value>
                <value>
                    <fullName>Realestate - Commercial</fullName>
                </value>
                <value>
                    <fullName>Motor Vehicle</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loan_to_ValueCC__c</fullName>
        <label>Loan to ValueCC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Industry_Category_IFRS_Self_Employed.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Retail trade</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>ICT</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <masterLabel>Industry Category - IFRS (Self-Employed)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Nature_of_Engagement_Self_Employed.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Professional service provider</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational service provider</fullName>
    </customValue>
    <customValue>
        <fullName>Trader</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Nature of Engagement (Self-Employed)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestRubiconProductDetailsController.cls
/**
 * @description       :
 * @author            : Travis Allen
 * @group             :
 * @last modified on  : 03-08-2021
 * @last modified by  : Travis Allen
 * Modifications Log
 * Ver   Date         Author         Modification
 * 1.0   03-08-2021   Travis Allen   Initial Version
 **/
@isTest
public inherited sharing class TestRubiconProductDetailsController {
  @testSetup
  public static void createData() {
    List<Opportunity> opList = TestDataFactory.CreateOpportunities(1);
    List<Account> accList = TestDataFactory.CreateBasicAccounts(3, 'Test');
    accList[0].Status_of_Address__pc = Constants.OWN;
    accList[0].Years_at_Residence__pc = 4;
    accList[0]
      .Highest_Level_of_Education_attained__pc = 'University: Post Graduate';
    accList[0].PersonBirthdate = date.newInstance(
      System.Today().year() - 36,
      2,
      11
    );
    accList[0].Type = 'Analyst';
    insert accList;
    Util.ExecutionCount = 2;

    opList[0].accountId = accList[0].id;
    opList[0].Collateral_CC__c = 'Cash';
    opList[0].Collateral_LOC__c = 'Cash';
    opList[0].Loan_to_ValueCC__c = 1;
    opList[0].StageName = 'Customer Interview';
    opList[0].CloseDate = Date.today().addDays(6);
    insert opList[0];

    List<Product2> products = new List<Product2>();
    List<String> families = new List<String>{ 'JN Bank Auto Loan' };
    for (String family : families) {
      //add each product to be created
      products.add(
        TestDataFactory.CreateProduct(family, 'iPhone X - ' + family)
      );
    }
    //Insert products with families
    insert products;

    //Instantiate the Pricebook2 record with StandardPricebookId
    Pricebook2 standardPricebook = new Pricebook2(
      Id = Test.getStandardPricebookId(),
      IsActive = true
    );

    //Execute an update DML on the Pricebook2 record, to make IsStandard to true
    update standardPricebook;

    //Query for the Pricebook2 record, to check IsStandard field
    standardPricebook = [
      SELECT Id, IsStandard
      FROM Pricebook2
      WHERE Id = :standardPricebook.Id
    ];
    //It should return true
    System.assertEquals(true, standardPricebook.IsStandard);

    List<PricebookEntry> priceBookEntries = new List<PricebookEntry>();
    for (Product2 record : products) {
      priceBookEntries.add(
        TestDataFactory.CreatePriceBookEntry(standardPricebook.Id, record.Id)
      );
    }
    //Insert Price Book Entries
    insert priceBookEntries;

    List<OpportunityLineItem> lineItems = new List<OpportunityLineItem>();
    for (PricebookEntry record : priceBookEntries) {
      lineItems.add(
        TestDataFactory.CreateOpportunityLineItem(opList[0].id, record.Id)
      );
    }
    // Insert Opportunity Line Items
    insert lineItems;

    FinServ__Employment__c employee = TestDataFactory.CreateEmployment(
      accList[0].id,
      'Employeement Test'
    );
    employee.Current_Employment__c = true;
    employee.FinServ__EmploymentStatus__c = 'Permanent';
    employee.Employment_Status__c = 'Contractual';
    employee.Industry__c = 'Financial Services';
    employee.Professional_Category__c = 'Professional';
    employee.Assessment_of_Business_Working_Capita__c = 'Good';
    employee.Nature_of_Engagement__c = 'Professional service provider';
    employee.Assessment_of_Business__c = Constants.THREE_TO_FOUR_YEARS_AND_OR;
    employee.Assessment_of_Statement__c = '	Strongly Supported';
    employee.Length_of_Trade__c = 'More than 5 years';
    Map<String, Id> recordTypeMap = Util.getRecordTypeids(
      'FinServ__Employment__c'
    );
    employee.RecordTypeId = recordTypeMap.get('Employed');
    insert employee;

    Applicant__c applicant = TestDataFactory.CreateApplicant(
      accList[0].id,
      opList[0].id
    );
    applicant.Credit_History_in_last_24_Months__c = 'No Delinquency';
    applicant.Assessment_of_Applicant_Net_Worth__c = 'Reasonable net worth';
    insert applicant;

    List<Supplementary_Card_Holders__c> cardHolderList = TestDataFactory.CreateSupplementaryCardHolders(
      2,
      opList[0].id
    );
    cardHolderList[0].Account__c = accList[1].id;
    cardHolderList[1].Account__c = accList[2].id;
    insert cardHolderList;

    List<Loan_Calculator__c> loanCalculationRecord = TestDataFactory.CreateLoanCalculation(
      1
    );
    insert loanCalculationRecord;

    List<Loan_Calculation_Product__c> loanCalculationProductRecord = TestDataFactory.CreateLoanCalculationProduct(
      1
    );
    loanCalculationProductRecord[0]
      .Loan_Calculation_Id__c = loanCalculationRecord[0].Id;
    loanCalculationProductRecord[0]
      .Approved_Starting_Limit_Number__c = 10000000;
    loanCalculationProductRecord[0].Legal_Fees_including_GCT_Number__c = 1000;
    loanCalculationProductRecord[0].Stamp_Duty_Number__c = 500;
    insert loanCalculationProductRecord;
  }

  @isTest
  public static void testSupplementaryCardHoldersMethod() {
    List<Opportunity> opList = [SELECT Id FROM Opportunity];
    Test.startTest();
    List<SupplementaryCardHolderWrapper> cardHoldersWrapper = RubiconProductDetailsController.getSupplementaryCardHolders(
      opList[0].id
    );
    System.assertEquals(2, cardHoldersWrapper.size());
    Test.stopTest();
  }

  @isTest
  public static void testProductFamilySelection() {
    List<Opportunity> opList = [SELECT Id FROM Opportunity];
    Test.startTest();
    Object productFamily = RubiconProductDetailsController.getSingleProductFamilySelection(
      opList[0].id
    );
    Test.stopTest();
  }

  @isTest
  public static void testGetIDMDataMap() {
    List<Opportunity> opList = [SELECT Id FROM Opportunity];
    Test.startTest();
    Object loanCalcRecord = RubiconProductDetailsController.getIDMProductDetails(
      opList[0].Id
    );
    System.assert(
      loanCalcRecord != null,
      'Loan Calculation Record Was not retrieved'
    );
    Test.stopTest();
  }

  @isTest
  public static void testGetApplicantDetails() {
    List<Opportunity> opList = [SELECT Id FROM Opportunity];
    Test.startTest();
    Object applicantRecord = RubiconProductDetailsController.getApplicantsDetails(
      opList[0].Id
    );
    System.assert(
      applicantRecord != null,
      'Applicant Record Was not retrieved'
    );
    Test.stopTest();
  }

  @isTest
  public static void testGetOpportunityDetails() {
    List<Opportunity> opList = [SELECT Id FROM Opportunity];
    Test.startTest();
    Object oppRecord = RubiconProductDetailsController.getOpportunityDetails(
      opList[0].Id
    );
    System.assert(oppRecord != null, 'Opportunity Record Was not retrieved');
    Test.stopTest();
  }

  @isTest
  public static void testGetPickListValues() {
    Test.startTest();

    List<String> names = new List<String>();

    names.add('Type');
    names.add('Highest_Level_of_Education_attained__pc');

    Object pickListValues = RubiconProductDetailsController.getPickListValuesList(
      'Account',
      names
    );
    System.assert(pickListValues != null, 'Picklists fields not being added.');
    Test.stopTest();
  }

  @isTest
  public static void testUpdateFieldsOnOpportunity() {
    List<Opportunity> opList = [SELECT Id, Amount FROM Opportunity];
    Map<String, Object> mapFields = new Map<String, Object>();
    mapFields.put('Amount', 10000);
    Test.startTest();
    Object result = RubiconProductDetailsController.updateFieldsOnOpportunity(
      opList[0].Id,
      mapFields
    );
    System.assert(
      result === Constants.SUCCESS,
      'Opportunity Record Was not updated'
    );
    Test.stopTest();
  }
}