mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/FinServ__Employment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Loan_Calculation_Product__c/Loan_Calculation_Product__c.object-meta.xml
<CustomObject>
    <description
  >Auto, Unsecured, Credit card, and Line of credit products for loan calculation.</description>
    <label>Loan Calculation Product</label>
    <nameField>
        <displayFormat>LCP-{000000}</displayFormat>
        <label>Loan Calculation Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculation Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/Loan_Calculator__c.object
<CustomObject>
    <label>Loan Calculation</label>
    <nameField>
        <displayFormat>LC-{000000000}</displayFormat>
        <label>Loan Calculator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OneJNEventService.cls
/**
 * @description       : service to coordinate the  selector layer and serialization
 * @author            : Remario Richards
 * @group             :
 * @last modified on  : 06-03-2021
 * @last modified by  : Ishwari Gaikwad(Thinqloud)
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   05-26-2021   Remario Richards   Initial Version
 **/
public with sharing class OneJNEventService {
  /**
   * @description
   * @author Ishwari Gaikwad(Thinqloud) | 06-03-2021
   * @param applicationList
   * @param opportunityList
   * @return OneJNSerializer
   **/
  public static String build(
    List<Application__c> applicationList,
    List<Opportunity> opportunityList
  ) {
    set<Id> opportunityIdSet = new Set<Id>();

    List<Account> accountList = new List<Account>();
    List<Applicant__c> applicantList = new List<Applicant__c>();
    List<Application__c> applicationsList = new List<Application__c>();
    List<Opportunity> opportunitysList = new List<Opportunity>();
    List<FinServ__Employment__c> employmentList = new List<FinServ__Employment__c>();
    List<OpportunityLineItem> oppLineItemList = new List<OpportunityLineItem>();
    List<Loan_Calculation_Product__c> loanCalcProductList = new List<Loan_Calculation_Product__c>();
    List<Loan_Calculator__c> loanCalculatorList = new List<Loan_Calculator__c>();

    if (!opportunityList.isEmpty() && opportunityList.size() > 0) {
      for (Opportunity app : opportunityList) {
        opportunityIdSet.add(app.Id);
      }
    } else {
      for (Application__c app : applicationList) {
        opportunityIdSet.add(app.Opportunity_Id__c);
      }
    }
    if (opportunityIdSet.size() > 0) {
      opportunitysList = OneJNQuerySelector.getOpportunity(opportunityIdSet);
      oppLineItemList = OneJNQuerySelector.getOpportunityLineItem(
        opportunityIdSet
      );
      applicationsList = OneJNQuerySelector.getApplications(opportunityIdSet);
      applicantList = OneJNQuerySelector.getApplicants(opportunityIdSet);
      if (applicantList.size() > 0) {
        Set<Id> accountIdSet = new Set<Id>();
        for (Applicant__c applicant : applicantList) {
          accountIdSet.add(applicant.Account__c);
        }
        if (accountIdSet.size() > 0) {
          accountList = OneJNQuerySelector.getAccounts(accountIdSet);
          employmentList = OneJNQuerySelector.getEmployment(accountIdSet);
        }
      }

      loanCalculatorList = OneJNQuerySelector.getLoanCalculations(
        opportunityIdSet
      );
      if (loanCalculatorList.size() > 0) {
        Set<Id> loanCalcIdSet = new Set<Id>();
        for (Loan_Calculator__c loanCalc : loanCalculatorList) {
          loanCalcIdSet.add(loanCalc.Id);
        }

        if (loanCalcIdSet.size() > 0) {
          loanCalcProductList = OneJNQuerySelector.getLoanCalculationProducts(
            loanCalcIdSet
          );
        }
      }
    }

    OneJNSerializer serialiser = new OneJNSerializer(
      applicantList[0],
      employmentList[0],
      accountList[0],
      applicationsList[0],
      opportunitysList[0],
      oppLineItemList[0],
      loanCalcProductList[0]
    );
    String JSONString = JSON.serialize(serialiser);
    return JSONString;
  }
}