mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRIF_Rating__c</fullName>
        <label>CRIF Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Risk_Rating_Scale</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreditInfo_Rating__c</fullName>
        <label>Credit Info Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Risk_Rating_Scale</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Applicant?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/FinServ__ReciprocalRole__c/FinServ__ReciprocalRole__c.object-meta.xml
<CustomObject>
    <description
  >Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <label>Reciprocal Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Risk_Rating_Scale.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Very Low Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Low Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Average Risk</fullName>
    </customValue>
    <customValue>
        <fullName>High Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Very High Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Score too low to rate</fullName>
    </customValue>
    <customValue>
        <fullName>Applicant too new to rate</fullName>
    </customValue>
    <masterLabel>Risk Rating Scale</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestApplicantTriggerHandler.cls
@isTest
public class TestApplicantTriggerHandler {
    
    @testSetup static void setup(){
        List<FinServ__ReciprocalRole__c> roles = new  List<FinServ__ReciprocalRole__c>();
        List<String> roleNames = new String[]{'Emergency Contact','Political Affiliation','JN Affiliation'};
            for(String roleName: roleNames){
                roles.add(TestDataFactory.CreateRole(roleName));
            }
        insert roles;
    }
    
    @isTest
    public static void shouldSetOverallCreditRating(){
        
        Account acc = TestDataFactory.CreateBasicAccounts(1, 'Richards')[0];
        insert acc;
        Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
        opp.AccountId = acc.Id;
        insert opp;
        
        List<Applicant__c> newApplicants = new List<Applicant__c>();
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very Low Risk', CreditInfo_Rating__c = 'Very Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very Low Risk', CreditInfo_Rating__c = 'Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very Low Risk', CreditInfo_Rating__c = 'Average Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very Low Risk', CreditInfo_Rating__c = 'Very High Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very Low Risk', CreditInfo_Rating__c = 'Score too low to rate'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very Low Risk', CreditInfo_Rating__c = 'Applicant too new to rate'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Low Risk', CreditInfo_Rating__c = 'Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Low Risk', CreditInfo_Rating__c = 'Very Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Low Risk', CreditInfo_Rating__c = 'Average Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Low Risk', CreditInfo_Rating__c = 'High Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Low Risk', CreditInfo_Rating__c = 'Score too low to rate'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Low Risk', CreditInfo_Rating__c = 'Applicant too new to rate'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Average Risk', CreditInfo_Rating__c = 'Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Average Risk', CreditInfo_Rating__c = 'Average Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Average Risk', CreditInfo_Rating__c = 'Very High Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Average Risk', CreditInfo_Rating__c = 'High Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Average Risk', CreditInfo_Rating__c = 'Score too low to rate'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Average Risk', CreditInfo_Rating__c = 'Applicant too new to rate'));
     	newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'High Risk', CreditInfo_Rating__c = 'Very Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'High Risk', CreditInfo_Rating__c = 'Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'High Risk', CreditInfo_Rating__c = 'Average Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'High Risk', CreditInfo_Rating__c = 'High Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'High Risk', CreditInfo_Rating__c = 'Very High Risk'));
		newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'High Risk', CreditInfo_Rating__c = 'Score too low to rate')); 
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'High Risk', CreditInfo_Rating__c = 'Applicant too new to rate'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very High Risk', CreditInfo_Rating__c = 'Very Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very High Risk', CreditInfo_Rating__c = 'Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very High Risk', CreditInfo_Rating__c = 'Average Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very High Risk', CreditInfo_Rating__c = 'High Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very High Risk', CreditInfo_Rating__c = 'Very High Risk'));
		newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very High Risk', CreditInfo_Rating__c = 'Score too low to rate')); 
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Very High Risk', CreditInfo_Rating__c = 'Applicant too new to rate'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Score too low to rate', CreditInfo_Rating__c = 'Very Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Score too low to rate', CreditInfo_Rating__c = 'Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Score too low to rate', CreditInfo_Rating__c = 'Average Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Score too low to rate', CreditInfo_Rating__c = 'High Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Score too low to rate', CreditInfo_Rating__c = 'Very High Risk'));
		newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Score too low to rate', CreditInfo_Rating__c = 'Score too low to rate')); 
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Score too low to rate', CreditInfo_Rating__c = 'Applicant too new to rate'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Applicant too new to rate', CreditInfo_Rating__c = 'Very Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Applicant too new to rate', CreditInfo_Rating__c = 'Low Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Applicant too new to rate', CreditInfo_Rating__c = 'Average Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Applicant too new to rate', CreditInfo_Rating__c = 'High Risk'));
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Applicant too new to rate', CreditInfo_Rating__c = 'Very High Risk'));
		newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Applicant too new to rate', CreditInfo_Rating__c = 'Score too low to rate')); 
        newApplicants.add(new Applicant__c(Account__c = acc.Id, Opportunity__c = opp.Id, CRIF_Rating__c = 'Applicant too new to rate', CreditInfo_Rating__c = 'Applicant too new to rate')); 
         
        insert newApplicants;
    }
    
    @isTest
    public static void shouldMaximumApplicantsOpportunity(){
        Integer count = 3;
        Test.startTest();
        List<Account> accounts = TestDataFactory.CreateBasicAccounts(count, 'ln');
        //Insert accounts
        insert accounts;
        
        List<Opportunity> opps = TestDataFactory.CreateOpportunities(count);
        for(Integer i = count-1; i >= 0 ; i--){
            opps[i].AccountId = accounts[i].Id;
        }
        // Insert opportunities
        insert opps;
        
        List<Applicant__c> applicants = new List<Applicant__c>();
        // Create applicant with opportunities
        for(Integer i = count-1; i >= 0 ; i--){
            applicants.add(TestDataFactory.CreateApplicant(accounts[0].Id, opps[0].Id));
        }
		// Insert Applicants
		insert applicants;
        update applicants;
        Test.stopTest();
    }
}