mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_of_Applicant_Net_Worth__c</fullName>
        <label>Assessment of Applicant Net Worth</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Strong net worth</fullName>
                </value>
                <value>
                    <fullName>Reasonable net worth</fullName>
                </value>
                <value>
                    <fullName>Low Net Worth</fullName>
                </value>
                <value>
                    <fullName>New worth not commensurate with age and earning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_History_in_last_24_Months__c</fullName>
        <label>Credit History in last 24 Months</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Delinquency</fullName>
                </value>
                <value>
                    <fullName>1 - 10 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>11 - 30 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>31 - 60 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>61 - 90 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>Over 90 Days Delinquent</fullName>
                </value>
                <value>
                    <fullName>No Credit History</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ApplicantDetailsWrapper.cls
public with sharing class ApplicantDetailsWrapper {

    @AuraEnabled
    public String creditHistoryInLast24Month;
    @AuraEnabled
    public String assessmentOfApplicantNetWorth; 

    public ApplicantDetailsWrapper(Applicant__c applicant) {
        this.creditHistoryInLast24Month = applicant.Credit_History_in_last_24_Months__c;
        this.assessmentOfApplicantNetWorth = applicant.Assessment_of_Applicant_Net_Worth__c;
    }
}