mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Personal_Expenses_Monthly_Prior_Loan__c</fullName>
        <label>Personal Expenses Monthly Prior Loan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rent_Strata_Maintenance__c</fullName>
        <label>Rent/Strata Maintenance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Motor_Vehicle_Monthly_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Motor_Vehicle_Monthly_Payment_Number__c</fullName>
    <label>Motor Vehicle Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Other_Asset_Monthly_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Other_Asset_Monthly_Payment_Number__c</fullName>
    <label>Other Asset Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Other_Loan_Monthly_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Other_Loan_Monthly_Payment_Number__c</fullName>
    <label>Other Loan Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Real_Estate_Monthly_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Real_Estate_Monthly_Payment_Number__c</fullName>
    <label>Real Estate Monthly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Savings_Pension_Insurance_Number__c.field-meta.xml
<CustomField>
    <fullName>Savings_Pension_Insurance_Number__c</fullName>
    <label>Savings/Pension/Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Statutory_Deductions_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Statutory_Deductions_Numbers__c</fullName>
    <label>Statutory Deductions</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ApplicantWrapper.cls
public with sharing class ApplicantWrapper {
  @AuraEnabled
  public String Id;
  @AuraEnabled
  public Date dob;
  @AuraEnabled
  public Integer age;
  @AuraEnabled
  public Decimal rating;
  @AuraEnabled
  public Boolean eligibleForCreditorLife;
  @AuraEnabled
  public Decimal salutaryDeductions;
  @AuraEnabled
  public Decimal rentStrataMaintenance;
  @AuraEnabled
  public Decimal personalMonthlyExpensesPriorLoan;
  @AuraEnabled
  public Decimal savingsPensionInsurance;
  @AuraEnabled
  public Decimal realEstateMonthlyPayment;
  @AuraEnabled
  public Decimal motorVehicleMonthlyRepayment;
  @AuraEnabled
  public Decimal otherAssetMonthlyPayment;
  @AuraEnabled
  public Decimal otherLoanMonthlyPayment;

  public ApplicantWrapper(Applicant__c record) {
    System.debug(record);
    this.Id = record.Id;
    if (record.Account__r != null) {
      this.dob = record.Account__r.PersonBirthdate;
      this.age = calculateAge(dob);
    }

    this.checkCreditorLifeEligibility();
    this.salutaryDeductions = record.Statutory_Deductions_Numbers__c;
    this.rentStrataMaintenance = record.Rent_Strata_Maintenance__c;
    this.personalMonthlyExpensesPriorLoan = record.Personal_Expenses_Monthly_Prior_Loan__c;
    this.savingsPensionInsurance = record.Savings_Pension_Insurance_Number__c;
    this.realEstateMonthlyPayment = record.Real_Estate_Monthly_Payment_Number__c;
    this.motorVehicleMonthlyRepayment = record.Motor_Vehicle_Monthly_Payment_Number__c;
    this.otherAssetMonthlyPayment = record.Other_Asset_Monthly_Payment_Number__c;
    this.otherLoanMonthlyPayment = record.Other_Loan_Monthly_Payment_Number__c;
  }

  private Integer calculateAge(Date dob) {
    Integer currentYear = Date.today().year();
    Integer currentMonth = Date.today().month();
    Integer currentDay = Date.today().day();
    Integer birthYear = dob.year();
    Integer birthMonth = dob.month();
    Integer birthDay = dob.day();
    Integer age = currentYear - birthYear;
    if (!(currentMonth >= birthMonth) && !(currentDay >= birthday)) {
      return age - 1;
    }
    return age;
  }

  private void checkCreditorLifeEligibility() {
    if (this.age > Constants.MAX_CREDITOR_LIFE_AGE) {
      this.eligibleForCreditorLife = false;
    } else {
      this.eligibleForCreditorLife = true;
    }
  }
}