mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/FinServ__Employment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_of_Business_Working_Capita__c</fullName>
        <description>Self employed persons</description>
        <label>Assessment of Business Working Capita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Adequate</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>Not Adequate</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assessment_of_Business__c</fullName>
        <description>Self employed</description>
        <label>Assessment of Business  Fin Performance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good growth and profit trends for 3 - 4 years</fullName>
                </value>
                <value>
                    <fullName>Good growth and profit trends for up to 2 years</fullName>
                </value>
                <value>
                    <fullName>Inconsistent profit/growth trends</fullName>
                </value>
                <value>
                    <fullName>Inadequate growth and/or profit trends</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assessment_of_Statement__c</fullName>
        <label>Assessment of Business Fin Statement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Supported</fullName>
                </value>
                <value>
                    <fullName>Adequately Supported</fullName>
                </value>
                <value>
                    <fullName>Sound Business Plan, Skill and Professional Competence</fullName>
                </value>
                <value>
                    <fullName>Weak Support or Doubtful</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Employment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Employment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Industry_Category_IFRS_Self_Employed</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_of_Trade__c</fullName>
        <label>Length of Trade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>More than 5 years</fullName>
                </value>
                <value>
                    <fullName>Between 3-5 years</fullName>
                </value>
                <value>
                    <fullName>Between 1-3 years</fullName>
                </value>
                <value>
                    <fullName>Less than a 1 year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nature_of_Engagement__c</fullName>
        <label>Nature of Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Nature_of_Engagement_Self_Employed</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Professional_Category__c</fullName>
        <label>Professional Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Officer</fullName>
                </value>
                <value>
                    <fullName>Clerical</fullName>
                </value>
                <value>
                    <fullName>Skilled Worker</fullName>
                </value>
                <value>
                    <fullName>Unskilled Worker</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/FinServ__EmploymentStatus__c.field-meta.xml
<CustomField>
    <fullName>FinServ__EmploymentStatus__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>Contractual</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Employed</fullName>
                <isActive>false</isActive>
                <label>Employed</label>
            </value>
            <value>
                <fullName>Home Maker</fullName>
                <isActive>false</isActive>
                <label>Home Maker</label>
            </value>
            <value>
                <fullName>Pensioner</fullName>
                <isActive>false</isActive>
                <label>Pensioner</label>
            </value>
            <value>
                <fullName>Retired</fullName>
                <isActive>false</isActive>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Self-Employed</fullName>
                <isActive>false</isActive>
                <label>Self-Employed</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
            <value>
                <fullName>Unemployed with Income</fullName>
                <isActive>false</isActive>
                <label>Unemployed with Income</label>
            </value>
            <value>
                <fullName>Unemployed without Income</fullName>
                <isActive>false</isActive>
                <label>Unemployed without Income</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__Employment__c/fields/FinServ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>FinServ__StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/Loan_Calculation_Product__c.object-meta.xml
<CustomObject>
    <description
  >Auto, Unsecured, Credit card, and Line of credit products for loan calculation.</description>
    <label>Loan Calculation Product</label>
    <nameField>
        <displayFormat>LCP-{000000}</displayFormat>
        <label>Loan Calculation Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculation Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Ability_to_Service_Before_Number__c.field-meta.xml
<CustomField>
    <fullName>Ability_to_Service_Before_Number__c</fullName>
    <description>Ability to Service Before (TDSR)</description>
    <label>Ability to Service Before</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Collateral_Type_List__c.field-meta.xml
<CustomField>
    <fullName>Collateral_Type_List__c</fullName>
    <description>Collateral Type</description>
    <label>Collateral Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsecured (None)</fullName>
            </value>
            <value>
                <fullName>Cash/Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_Calculation_Id__c.field-meta.xml
<CustomField>
    <fullName>Loan_Calculation_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan calculation</description>
    <label>Loan Calculation</label>
    <referenceTo>Loan_Calculator__c</referenceTo>
    <relationshipLabel>Loan Calculation Products</relationshipLabel>
    <relationshipName>Loan_Calculation_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_to_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_to_Value_Number__c</fullName>
    <description>Loan to Value</description>
    <label>Loan to Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Repayment_Method_List__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Method_List__c</fullName>
    <description>Repayment Method</description>
    <label>Repayment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salary Deduction</fullName>
            </value>
            <value>
                <fullName>Standing Order</fullName>
            </value>
            <value>
                <fullName>Over The Counter</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Dividends</fullName>
            </value>
            <value>
                <fullName>Alimony</fullName>
            </value>
            <value>
                <fullName>Remittances</fullName>
            </value>
            <value>
                <fullName>Rental Income</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Requested_Credit_Limit_Number__c.field-meta.xml
<CustomField>
    <fullName>Requested_Credit_Limit_Number__c</fullName>
    <description>Requested Credit Limit</description>
    <label>Requested Credit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <description>Auto loan product</description>
    <label>Auto</label>
</RecordType>

mdapipkg/Scratch/objects/Loan_Calculator__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Calculations</relationshipLabel>
        <relationshipName>Loan_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Calculation</label>
    <nameField>
        <displayFormat>LC-{000000000}</displayFormat>
        <label>Loan Calculator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculations</pluralLabel>
    <recordTypes>
        <fullName>Product_Details</fullName>
        <active>true</active>
        <label>Product Details</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Details__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Details</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Loan_Calculator__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Product Details</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Loan_Calculator__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Opportunity/recordTypes/Mortgage.recordType-meta.xml
<RecordType>
    <fullName>Mortgage</fullName>
    <active>true</active>
    <businessProcess>Test Mortgage Process</businessProcess>
    <label>Mortgage, IPF, Commercial Auto Loan, Cash Secured Loan</label>
</RecordType>

force-app/main/default/globalValueSets/Industry_Category_IFRS_Self_Employed.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Retail trade</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>ICT</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <masterLabel>Industry Category - IFRS (Self-Employed)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Nature_of_Engagement_Self_Employed.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Professional service provider</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational service provider</fullName>
    </customValue>
    <customValue>
        <fullName>Trader</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Nature of Engagement (Self-Employed)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/JN1_4287_TestClass.cls
@isTest
public class JN1_4287_TestClass {
    //User
    public static User testUser;
    
    //Account
    public static Account testAccountObj;
    public static list<Account> testAccountObjs;
    
    //Loan Calculator
    public static Loan_Calculator__c testLoanCalculatorObj;
    public static List<Loan_Calculator__c> testLoanCalculatorLst;
    
    //Opportunity
    public static Opportunity testOpportunityObj;
    public static List<Opportunity> testOpportunityLst;
    
    //Loan_Calculation_Product__c
    public static Loan_Calculation_Product__c testLoanCalculationProductObj;
    public static List<Loan_Calculation_Product__c> testLoanCalculationProductLst;
	
    //Loan_Calculation_Applicant_Product__c
    public static Loan_Calculation_Applicant_Product__c testLoanCalculationApplicationProductObj;
    public static List<Loan_Calculation_Applicant_Product__c> testLoanCalculationApplicationProductLst;
    
    //Employment
    public static FinServ__Employment__c testEmploymentObj;
    public static List<FinServ__Employment__c> testEmploymentLst;
  
    //Applicant
    public static Applicant__c testApplicantObj;    

    //Product2    
    public static Product2 prodctObj;
    
    //Price book 2    
    public static Pricebook2 priceBook2Obj; 
    
    //Price book Entry    
    public static PricebookEntry PricebookEntryObj;
    
    //Opportunity Line Item
    public static OpportunityLineItem testOpportunityLineItemObj;

    public static void CreateData(){                      
        //------Create User--------//
        testUser = TestDataFactory.CreateUser('testUserSunil@test.com');
        
        //------Create Account--------//
        Date dt = Date.newInstance(1995,11,13);
        testAccountObjs = TestDataFactory.CreateBasicAccounts(1, 'lastName');
        testAccountObj = testAccountObjs.get(0);
        testAccountObj.Political_Exposure__pc = False;
        testAccountObj.Jamaican_Tax_Registration_Number__pc = '123456789';
        testAccountObj.PersonBirthdate = Date.newInstance(1984, 02, 14);
        testAccountObj.Highest_Level_of_Education_attained__pc = 'High School';
        testAccountObj.Status_of_Address__pc='Own (without mortgage)';
        testAccountObj.Years_at_Residence__pc = 4;
        insert testAccountObj;
        
        //------Create Loan Calculator--------//
        Map<String, Id> recordTypeids = Util.getRecordTypeids('Loan_Calculator__c');
        testLoanCalculatorLst = TestDataFactory.CreateLoanCalculation(1);
        testLoanCalculatorObj = testLoanCalculatorLst.get(0);
        testLoanCalculatorObj.RecordTypeId = recordTypeids.get('Product_Details');
        insert testLoanCalculatorObj;
        
        //------Create Opportunity--------//
        testOpportunityLst = TestDataFactory.CreateOpportunities(1);
        testOpportunityObj = testOpportunityLst.get(0);
        testOpportunityObj.AccountId = testAccountObj.Id;
        testOpportunityObj.Product_Details__c = testLoanCalculatorObj.Id;
        testOpportunityObj.StageName ='Submitted and Processing'; 
        insert testOpportunityObj;
        testLoanCalculatorObj.Opportunity__c = testOpportunityObj.Id;
        update testLoanCalculatorObj;
        
        //------Create Loan Calculation Product--------//
        testLoanCalculationProductLst = TestDataFactory.CreateLoanCalculationProduct(1);
        testLoanCalculationProductObj = testLoanCalculationProductLst.get(0);
        testLoanCalculationProductObj.Loan_Calculation_Id__c = testLoanCalculatorObj.Id;
        testLoanCalculationProductObj.Requested_Credit_Limit_Number__c = 500;
        testLoanCalculationProductObj.Collateral_Type_List__c = 'Cash/Investments';
        testLoanCalculationProductObj.Loan_to_Value_Number__c = 26;
        testLoanCalculationProductObj.Ability_to_Service_Before_Number__c = 25;
        testLoanCalculationProductObj.Repayment_Method_List__c = 'Salary Deduction';
        insert testLoanCalculationProductObj;

        //------Create Employement--------//
        testEmploymentObj = TestDataFactory.CreateEmployment(testAccountObj.Id, 'name');
        testEmploymentObj.FinServ__StartDate__c = Date.newInstance(2010,11,13);
        testEmploymentObj.Current_Employment__c = True;
        testEmploymentObj.FinServ__EmploymentStatus__c = 'Permanent';
        testEmploymentObj.Industry__c='Financial Services';
        testEmploymentObj.Professional_Category__c = 'Professional';
        testEmploymentObj.Assessment_of_Business_Working_Capita__c = 'Good';
        testEmploymentObj.Nature_of_Engagement__c = 'Professional service provider';
        testEmploymentObj.Assessment_of_Business__c = 'Good growth and or profit trends for 3 - 4 years';
        testEmploymentObj.Assessment_of_Statement__c = 'Strongly Supported';
        testEmploymentObj.Length_of_Trade__c = 'More than 5 years';
        testEmploymentObj.Account__c = testAccountObj.Id;
        
        insert testEmploymentObj;
        
        //------Create Application--------//
        testApplicantObj = TestDataFactory.CreateApplicant(testAccountObj.Id, testOpportunityObj.Id);
        testApplicantObj.Sanction_Screening_has_Negative_Trace__c = 'No';
        testApplicantObj.Account__c = testAccountObj.Id;
        testApplicantObj.Opportunity__c = testOpportunityObj.Id;
        testApplicantObj.Credit_History_in_last_24_Months__c = '1 - 10 Days Delinquent';
        testApplicantObj.Assessment_of_Applicant_Net_Worth__c = 'Strong net worth';
        
        insert testApplicantObj;
        
        //------Create Loan Calculation Application Product--------//
        testLoanCalculationApplicationProductLst = TestDataFactory.CreateLoanCalculationApplicationPrdct(1);
        testLoanCalculationApplicationProductObj = testLoanCalculationApplicationProductLst.get(0);
        testLoanCalculationApplicationProductObj.Loan_Calculation_Product_Id__c = testLoanCalculationProductObj.Id;
        testLoanCalculationApplicationProductObj.Loan_Amount_Number__c = 56;
        testLoanCalculationApplicationProductObj.Applicant_Id__c = testApplicantObj.id;
        insert testLoanCalculationApplicationProductObj;
        
        //------Create Product--------//
        prodctObj = TestDataFactory.CreateProduct('JN Bank Auto Loan', 'JN Bank Auto Loan');
        prodctObj.QuantityUnitOfMeasure = 'Each';
        insert prodctObj;
        
        //------Create Pricebook2--------//
        priceBook2Obj = New Pricebook2(Id = Test.getStandardPricebookId(), 
                                       IsActive = true);
        Update priceBook2Obj;
        
        //------Create PriceBookEntry--------//
        PricebookEntryObj = TestDataFactory.CreatePriceBookEntry(priceBook2Obj.Id, prodctObj.Id);
        insert PricebookEntryObj;
        
        //------Create Opportunity Line Item--------//
        testOpportunityLineItemObj = TestDataFactory.CreateOpportunityLineItem(testOpportunityObj.Id, PricebookEntryObj.Id);
        insert testOpportunityLineItemObj;
    }
    
    @isTest
    public static void test1_AutoCreditScoreModelPage(){
        CreateData();
        Test.StartTest();
        pageReference pager = page.AutoCreditScoreModel;
        pager.getParameters().put('id', String.valueOf(testApplicantObj.Id));
        Test.setCurrentPage(pager);
        AutoCreditScoreModelController testAccPlan = new AutoCreditScoreModelController();
        
        System.assertEquals('Test 0 lastNamei', testAccPlan.nameOfApplicant, 'Name of Applicant Not matching');
        System.assertEquals('No', testAccPlan.isApplicantPolicExpoxed, 'Is the Applicant a Politcally Exposed Person (PEP)?* Not matching');
        System.assertEquals('123456789', testAccPlan.jamaicanTaxNumber, 'jamaicanTaxNumber Not matching');
        System.assertEquals('No', testAccPlan.hasSanctionNegativeTrace, 'Has the sanction screening(s) resulted in a negative trace?* Not matching');
        
        System.assertEquals('31-40', testAccPlan.ageString, 'Age Score Not matching');
        System.assertEquals(600, testAccPlan.ageScore, 'Age Score Not matching');
        System.assertEquals(18, testAccPlan.ageWeightage, 'Age Weightage Not matching');
        
        System.assertEquals('High School', testAccPlan.educationString, 'Education Not matching');
        System.assertEquals(400, testAccPlan.educationScore, 'Education Score Not matching');
        System.assertEquals(16, testAccPlan.educationWeightage, 'Education Weightage Not matching');

        Test.StopTest(); 
    }
}