mdapipkg/Scratch/objects/Application_Asset_Liability__c.object
<CustomObject>
    <fields>
        <fullName>Monthly_Payment_After__c</fullName>
        <description>Property, Vehicle, Other Asset, Other Loan
This field maps to Monthly_payment__c from assets and liabilities object</description>
        <label>Monthly Payment After</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Payment_Prior__c</fullName>
        <description>Property, Vehicle, Other Asset, Other Loan</description>
        <label>Monthly Payment Prior</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Applicant Asset/Liability</label>
    <nameField>
        <displayFormat>AAL-{0000000000}</displayFormat>
        <label>Application Assets</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Assets//Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Asset_Liability__c/fields/Minimum_Payment_After_Calc__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Payment_After_Calc__c</fullName>
    <formula
  >$CustomMetadata.JN_Defaults__mdt.Default.Average_Balance_Minimum_Pay_Number__c * 
IF(
OR(
ISPICKVAL(Treatment_of_Credit_LOC_list__c, &quot;Repay Facility&quot;),
ISPICKVAL(Treatment_of_Credit_LOC_list__c, &quot;Will Remain&quot;)),
Assets_and_Liabilities__r.Average_Monthly_Usage__c,
IF(
(ISPICKVAL(Treatment_of_Credit_LOC_list__c, &quot;Close Facility&quot;)),0,
IF(ISNULL(Assets_and_Liabilities__r.Average_Monthly_Usage__c),0,Assets_and_Liabilities__r.Average_Monthly_Usage__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minimum Payment After</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application_Asset_Liability__c/fields/Minimum_Payment_Calc__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Payment_Calc__c</fullName>
    <formula
  >$CustomMetadata.JN_Defaults__mdt.Default.Average_Balance_Minimum_Pay_Number__c *  IF (ISNULL(Assets_and_Liabilities__r.Average_Monthly_Usage__c),0,Assets_and_Liabilities__r.Average_Monthly_Usage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minimum Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ApplicantAssetsAndLiabilitiesWrapper.cls
public with sharing class ApplicantAssetsAndLiabilitiesWrapper {
  @AuraEnabled
  public String Id;
  @AuraEnabled
  public Decimal monthlyLoanPaymentPrior; //JN1-3967
  @AuraEnabled
  public Decimal monthlyLoanPaymentAfter; //JN1-3967
  @AuraEnabled
  public Decimal minimumPaymentPrior; //JN1-3967
  @AuraEnabled
  public Decimal minimumPaymentAfter; //JN1-3967

  public ApplicantAssetsAndLiabilitiesWrapper(
    Application_Asset_Liability__c record
  ) {
    //System.debug(record);
    this.Id = record.Id;
    this.monthlyLoanPaymentPrior = record.Monthly_Payment_Prior__c; //JN1-3967
    this.monthlyLoanPaymentAfter = record.Monthly_Payment_After__c; //JN1-3967
    this.minimumPaymentPrior = record.Minimum_Payment_Calc__c; //JN1-3967
    this.minimumPaymentAfter = record.Minimum_Payment_After_Calc__c; //JN1-3967
  }
}