mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculation_Product__c/Loan_Calculation_Product__c.object-meta.xml
<CustomObject>
    <description
  >Auto, Unsecured, Credit card, and Line of credit products for loan calculation.</description>
    <label>Loan Calculation Product</label>
    <nameField>
        <displayFormat>LCP-{000000}</displayFormat>
        <label>Loan Calculation Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculation Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Credit_Report_Fee_Number__c.field-meta.xml
<CustomField>
    <fullName>Credit_Report_Fee_Number__c</fullName>
    <label>Credit Report Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Creditor_Life_Insurance_Premium_Number__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Life_Insurance_Premium_Number__c</fullName>
    <description>JN Life Creditor Life Insurance Premium</description>
    <label>JN Life Creditor Life Insurance Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Interest_Rate_Number__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Number__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Legal_Fees_including_GCT_Number__c.field-meta.xml
<CustomField>
    <fullName>Legal_Fees_including_GCT_Number__c</fullName>
    <description>Legal Fees(including GCT)</description>
    <label>Legal Fees(including GCT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_Amount_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_Number__c</fullName>
    <description>Loan Amount for product</description>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Method_of_Fee_Payment_List__c.field-meta.xml
<CustomField>
    <fullName>Method_of_Fee_Payment_List__c</fullName>
    <label>Method of Fee Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Added to Loan</fullName>
            </value>
            <value>
                <fullName>Deducted from Loan</fullName>
            </value>
            <value>
                <fullName>Deduct from JN Account</fullName>
            </value>
            <value>
                <fullName>Paid out of Pocket</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Minimum_Payment_per_Credit_Limit_Number__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Payment_per_Credit_Limit_Number__c</fullName>
    <description>Minimum Payment as per Credit Limit</description>
    <label>Minimum Payment as per Credit Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Monthly_Compulsory_Savings_Number__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Compulsory_Savings_Number__c</fullName>
    <label>Monthly Compulsory Savings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Months_Number__c.field-meta.xml
<CustomField>
    <fullName>Months_Number__c</fullName>
    <label>Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Processing_Fees_including_GCT_Number__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fees_including_GCT_Number__c</fullName>
    <label>Processing Fees (including GCT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Requested_Credit_Limit_Number__c.field-meta.xml
<CustomField>
    <fullName>Requested_Credit_Limit_Number__c</fullName>
    <description>Requested Credit Limit</description>
    <label>Requested Credit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Closing_Costs_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Closing_Costs_Number__c</fullName>
    <description>Total Closing Costs</description>
    <label>Total Closing Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Monthly_Loan_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Loan_Payment_Number__c</fullName>
    <description>Total Monthly Loan Payment</description>
    <label>Total Monthly Loan Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Monthly_PI_Loan_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_PI_Loan_Payment_Number__c</fullName>
    <description>Total Monthly P&amp;I Loan Payment</description>
    <label>Total Monthly P&amp;I Loan Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

mdapipkg/Scratch/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT(PricebookEntry.Product2.Family)</formula>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/OneJNDeserializer.cls
/**
 * @description       :
 * @author            : Remario Richards
 * @group             :
 * @last modified on  : 06-03-2021
 * @last modified by  : Trupti Zende (Thinqloud)
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   05-26-2021   Remario Richards   Initial Version
 **/
public class OneJNDeserializer {
    public Loan_Calculation_Product__c loanCalculationProductRecord{get; set;}
    public Applicant__c primaryApplicantRecord{get; set;}
    public Applicant__c coApplicantRecord{get; set;}
    public Application__c applicationRecord{get; set;}
    public OpportunityLineItem opportunityLineItemRecord{get; set;}
    public Opportunity opportunityRecord{get; set;}

    class ConsolidatedReportWrapper{
        @AuraEnabled
        Public GeneralInformationWrapper generalInformation;
        @AuraEnabled
        Public ApplicantDetailsWrapper applicantDetailsPrimary;
        @AuraEnabled
        Public ApplicantDetailsWrapper[] applicantDetailsCoApplicants;
        @AuraEnabled
        Public LoanRequirementWrapper loanParameters;
        @AuraEnabled
        Public LoanFeesWrapper loanFees;
        @AuraEnabled
        Public String finalAssessmentReport;
        @AuraEnabled
        Public decimal nBrokenRules;

    }
    class GeneralInformationWrapper{
        @AuraEnabled
        Public String applicationID;
        @AuraEnabled
        Public String productType;
        @AuraEnabled
        Public String cardType;
        @AuraEnabled
        Public String preAssessmentDecision;
        @AuraEnabled
        Public String finalAssessmentDecision;
        @AuraEnabled
        Public Date requestDate;
        
    }
    class ApplicantDetailsWrapper{
        @AuraEnabled
        Public String rim;
        @AuraEnabled
        Public String fullName;
        @AuraEnabled
        Public decimal jNRiskScore;
        @AuraEnabled
        Public String jNRiskGrade;
        @AuraEnabled
        Public decimal cRBScore_CIJ;
        @AuraEnabled
        Public String cRBGrade_CIJ;
        @AuraEnabled
        Public decimal cRBScore_CRIF;
        @AuraEnabled
        Public String cRBGrade_CRIF;
        @AuraEnabled
        Public DocumentRequirementsWrapper[] documentRequirements;
    }
    class LoanRequirementWrapper{
        @AuraEnabled
        Public decimal approvedLoanAmount;
        @AuraEnabled
        Public decimal aprrovedCreditCardLimit;
        @AuraEnabled
        Public decimal approvedTenure;
        @AuraEnabled
        Public decimal approvedInterestRate;
        @AuraEnabled
        Public decimal monthlyPrincipalandInterest;
        @AuraEnabled
        Public decimal contractualSavings;
        @AuraEnabled
        Public decimal totalMonthlyPayments;
        @AuraEnabled
        Public decimal estimateOfMinimumPayment;
        @AuraEnabled
        Public decimal requestedLoanAmount;
    }
    class LoanFeesWrapper{
        @AuraEnabled
        Public String financingOption;
        @AuraEnabled
        Public decimal creditReportFee;
        @AuraEnabled
        Public decimal processingFee;
        @AuraEnabled
        Public decimal creditLifeSinglePremium;
        @AuraEnabled
        Public decimal legalFeesandStampduty;
        @AuraEnabled
        Public decimal totalFees;
        
    }
    class DocumentRequirementsWrapper{
        @AuraEnabled
        Public string documents;
        
    }
    /**
    * @description to deserialize the incoming json repsonse
    * @author Trupti Zende (Thinqloud) | 06-03-2021 
    * @param json 
    * @return ConsolidatedReportWrapper 
    **/
    public void parse(String response){
        Type resultType = Type.forName('ConsolidatedReportWrapper');
        ConsolidatedReportWrapper deserializeResults =       (ConsolidatedReportWrapper)JSON.deserialize(response, resultType);
        //return (ConsolidatedReportWrapper) System.JSON.deserialize(response, resultType);

        this.applicationRecord.Application_ID__c = deserializeResults.generalInformation.applicationID;
        this.applicationRecord.IDM_Amount_number__c = deserializeResults.loanParameters.requestedLoanAmount;
        this.applicationRecord.IDM_Number_of_Rules_Breached_Number__c = deserializeResults.nBrokenRules;


        //this.opportunityLineItemRecord.Product_Family__c = deserializeResults.generalInformation.productType; field is not writable
        //this.opportunityLineItemRecord.Name = deserializeResults.generalInformation.cardType;

        this.opportunityRecord.Pre_Approval_list__c = deserializeResults.generalInformation.preAssessmentDecision;
        this.opportunityRecord.Pre_Approval_list__c = deserializeResults.generalInformation.preAssessmentDecision;
        this.opportunityRecord.Final_Assessment_Decision_list__c = deserializeResults.generalInformation.finalAssessmentDecision;

        //deserializeResults.applicantDetailsPrimary.rim;
        this.primaryApplicantRecord.Account__c = deserializeResults.applicantDetailsPrimary.fullName;
        //this.primaryApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsPrimary.jNRiskGrade;
        //this.primaryApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsPrimary.jNRiskScore;
        //this.primaryApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsPrimary.cRBGrade_CIJ;
        //this.primaryApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsPrimary.cRBScore_CIJ;
        //this.primaryApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsPrimary.cRBGrade_CRIF;
        //this.primaryApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsPrimary.cRBScore_CRIF;
        // documents 

        //deserializeResults.applicantDetailsPrimary.rim;
        this.coApplicantRecord.Account__c = deserializeResults.applicantDetailsPrimary.fullName;
        //this.coApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsCoApplicants.jNRiskGrade;
        //this.coApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsCoApplicants.jNRiskScore;
        //this.coApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsCoApplicants.cRBGrade_CIJ;
        //this.coApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsCoApplicants.cRBScore_CIJ;
        //this.coApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsCoApplicants.cRBGrade_CRIF;
        //this.coApplicantRecord._NewFieldsToBeCreated_ = deserializeResults.applicantDetailsCoApplicants.cRBScore_CRIF;
        // documents 

        //this.requestDate = ;unix system date 


        this.loanCalculationProductRecord.Loan_Amount_Number__c = deserializeResults.loanParameters.approvedLoanAmount;
        this.loanCalculationProductRecord.Requested_Credit_Limit_Number__c = deserializeResults.loanParameters.aprrovedCreditCardLimit;
        this.loanCalculationProductRecord.Months_Number__c = deserializeResults.loanParameters.approvedTenure;
        this.loanCalculationProductRecord.Interest_Rate_Number__c = deserializeResults.loanParameters.approvedInterestRate;
        this.loanCalculationProductRecord.Total_Monthly_PI_Loan_Payment_Number__c = deserializeResults.loanParameters.monthlyPrincipalandInterest;
        this.loanCalculationProductRecord.Monthly_Compulsory_Savings_Number__c	 = deserializeResults.loanParameters.contractualSavings;
        this.loanCalculationProductRecord.Total_Monthly_Loan_Payment_Number__c = deserializeResults.loanParameters.totalMonthlyPayments;
        this.loanCalculationProductRecord.Minimum_Payment_per_Credit_Limit_Number__c = deserializeResults.loanParameters.estimateOfMinimumPayment;

        this.loanCalculationProductRecord.Method_of_Fee_Payment_List__c = deserializeResults.loanFees.financingOption;
        this.loanCalculationProductRecord.Credit_Report_Fee_Number__c = deserializeResults.loanFees.creditReportFee;
        this.loanCalculationProductRecord.Processing_Fees_including_GCT_Number__c = deserializeResults.loanFees.processingFee;
        this.loanCalculationProductRecord.Creditor_Life_Insurance_Premium_Number__c = deserializeResults.loanFees.creditLifeSinglePremium;
        this.loanCalculationProductRecord.Legal_Fees_including_GCT_Number__c = deserializeResults.loanFees.legalFeesandStampduty;
        this.loanCalculationProductRecord.Total_Closing_Costs_Number__c = deserializeResults.loanFees.totalFees;


        //deserializeResults.finalAssessmentReport;
    }

    
}