mdapipkg/Scratch/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Applicable_sources_of_income__c</fullName>
        <label>Applicable sources of income</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salary</fullName>
                </value>
                <value>
                    <fullName>Net Profit (Sole Trader)</fullName>
                </value>
                <value>
                    <fullName>Director&apos;s Emoluments (Director)</fullName>
                </value>
                <value>
                    <fullName>Share of Profits (Partnership)</fullName>
                </value>
                <value>
                    <fullName>Share of Profit (Shareholder)</fullName>
                </value>
                <value>
                    <fullName>Pension</fullName>
                </value>
                <value>
                    <fullName>Property Rental</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Director_s_Emoluments_Director__c</fullName>
        <label>Director’s Emoluments - Director</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Existing_Real_Estate_Rental_I__c</fullName>
        <description>(where rental property not treated as business)</description>
        <label>Existing Real Estate Rental I</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Monthly_Income__c</fullName>
        <label>Gross Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Life_Insurance_Cash_Value__c</fullName>
        <label>Life Insurance (Cash Value)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Profit_Sole_Trader__c</fullName>
        <label>Net Profit - Sole Trader</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Other_Income__c</fullName>
        <label>Other Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pension_IRS_Total_Contribution__c</fullName>
        <label>Pension/IRS (Total Contribution)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pension__c</fullName>
        <label>Pension</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Savings_Deposit_Investments__c</fullName>
        <label>Savings/Deposit/Investments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Share_of_Profit_Partnership__c</fullName>
        <label>Share of Profit - Partnership</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Share_of_Profit_Shareholder__c</fullName>
        <label>Share of Profit - Shareholder</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>App-{000000000}</displayFormat>
        <label>Applicant Details  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Motor_Vehicle_Market_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Motor_Vehicle_Market_Value_Number__c</fullName>
    <label>Motor Vehicle Market Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Other_Asset_Market_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Other_Asset_Market_Value_Number__c</fullName>
    <label>Other Asset Market Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Other_Loan_Loan_Balance_Number__c.field-meta.xml
<CustomField>
    <fullName>Other_Loan_Loan_Balance_Number__c</fullName>
    <label>Other Loan Loan Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Real_Estate_Market_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Real_Estate_Market_Value_Number__c</fullName>
    <label>Real Estate Market Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Statutory_Deductions_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Statutory_Deductions_Numbers__c</fullName>
    <label>Statutory Deductions</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FinancialDetailsSelector.cls
public with sharing class FinancialDetailsSelector {
  /**
   * Returns all the unverified fields for an applicant financial details
   * @param {Id} accountId - account Id
   * @return {AccountWrapper} - account details in wrapper format
   */
  public static FinancialDetailsWrapper financialDetailsSelector(Id oppId) {
    FinancialDetailsWrapper financialDetailWrapper;
    Applicant__c applicantObj = [
      SELECT
        Id,
        Real_Estate_Market_Value_Number__c,
        Motor_Vehicle_Market_Value_Number__c,
        Savings_Deposit_Investments__c,
        Life_Insurance_Cash_Value__c,
        Pension_IRS_Total_Contribution__c,
        Other_Asset_Market_Value_Number__c,
        Mortgage_Balance_Number__c,
        Other_Loan_Loan_Balance_Number__c,
        Average_Credit_Card_Balances_Number__c,
        Average_Line_of_Credit_Balance_Number__c,
        Other_Debt_Number__c,
        Mortgage_Rent_Number__c,
        Utilties_and_Household_Expenses_Number__c,
        Personal_and_Family_Expenses_Number__c,
        Transportation_Number__c,
        Other_Expenses_Number__c,
        Statutory_Deductions_Numbers__c,
        Total_Expenses_Calc__c,
        Applicable_sources_of_income__c,
        Gross_Monthly_Income__c,
        Other_Income__c,
        Net_Profit_Sole_Trader__c,
        Share_of_Profit_Partnership__c,
        Share_of_Profit_Shareholder__c,
        Director_s_Emoluments_Director__c,
        Pension__c,
        Existing_Real_Estate_Rental_I__c,
        Total_Assets_Calc__c,
        Total_Liabilities_Calc__c,
        Net_Worth_Calc__c
      FROM Applicant__c
      WHERE Opportunity__c = :oppId
    ];
    System.debug('Applicant Fileds ' + applicantObj);
    if (applicantObj != null) {
      financialDetailWrapper = new FinancialDetailsWrapper(applicantObj);
    }

    return financialDetailWrapper;
  }
}