mdapipkg/Scratch/objects/Creditor_Life_Matrix__mdt.object
<CustomObject>
    <fields>
        <fullName>X0_5__c</fullName>
        <label>0.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X10__c</fullName>
        <label>10</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_5__c</fullName>
        <label>1.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1__c</fullName>
        <label>1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_5__c</fullName>
        <label>2.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2__c</fullName>
        <label>2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3_5__c</fullName>
        <label>3.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3__c</fullName>
        <label>3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X4_5__c</fullName>
        <label>4.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X4__c</fullName>
        <label>4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X5_5__c</fullName>
        <label>5.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X5__c</fullName>
        <label>5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X6_5__c</fullName>
        <label>6.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X6__c</fullName>
        <label>6</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X7_5__c</fullName>
        <label>7.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X7__c</fullName>
        <label>7</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X8_5__c</fullName>
        <label>8.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X8__c</fullName>
        <label>8</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X9_5__c</fullName>
        <label>9.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X9__c</fullName>
        <label>9</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Creditor Life Matrix</label>
    <pluralLabel>Creditor Life Matrix</pluralLabel>
</CustomObject>

force-app/main/default/objects/JN_Defaults__mdt/JN_Defaults__mdt.object-meta.xml
<CustomObject>
    <description>custom meta data type to represent all the JN defaults.</description>
    <label>JN Defaults</label>
    <pluralLabel>JN Defaults</pluralLabel>
</CustomObject>

force-app/main/default/objects/JN_Defaults__mdt/fields/GCT__c.field-meta.xml
<CustomField>
    <fullName>GCT__c</fullName>
    <label>GCT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/JNConfigurations.cls
public with sharing class JNConfigurations {
  /**
   * gets the default jn configurations
   * @return {JNConfiguration}
   */
  @AuraEnabled
  public static JNConfiguration GetDefaultConfiguration() {
    try {
      List<JN_Defaults__mdt> records = [
        SELECT Id, GCT__c
        FROM JN_Defaults__mdt
        WHERE Label = :Constants.DEFAULT_METADATA_LABEL
      ];
      System.assert(records.size() == 1, 'default custom meta type size ');
      JN_Defaults__mdt record = records[0];
      return new JNConfiguration(record);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * retrieves creditor life rating for a list of applicants
   * @return {List<CreditorLifeMatrixWrapper> }
   */

  @AuraEnabled
  public static List<CreditorLifeMatrixWrapper> getCreditorLifeMatrix() {
    List<CreditorLifeMatrixWrapper> wrappers = new List<CreditorLifeMatrixWrapper>();
    List<Creditor_Life_Matrix__mdt> creditorLifeMatrices = [
      SELECT
        Label,
        X0_5__c,
        X1__c,
        X1_5__c,
        X2__c,
        X2_5__c,
        X3__c,
        X3_5__c,
        X4__c,
        X4_5__c,
        X5__c,
        X5_5__c,
        X6__c,
        X6_5__c,
        X7__c,
        X7_5__c,
        X8__c,
        X8_5__c,
        X9__c,
        X9_5__c,
        X10__c
      FROM Creditor_Life_Matrix__mdt
    ];
    for (Creditor_Life_Matrix__mdt record : creditorLifeMatrices) {
      CreditorLifeMatrixWrapper wrapper = new CreditorLifeMatrixWrapper(record);
      wrappers.add(wrapper);
    }
    return wrappers;
  }
}