mdapipkg/Scratch/objects/Credit_Rating__mdt.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Max__c</fullName>
        <label>Credit Score Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Min__c</fullName>
        <label>Credit Score Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Credit Rating</label>
    <pluralLabel>Credit Rating</pluralLabel>
</CustomObject>

force-app/main/default/classes/RiskRatingWrapper.cls
public  class RiskRatingWrapper {
   @AuraEnabled
   public Decimal score;
   @AuraEnabled
   public String rating;
   @AuraEnabled
   public String classification;
   @AuraEnabled
   public List<Credit_Rating__mdt> creditRatingList = new List<Credit_Rating__mdt>();

   public RiskRatingWrapper(Decimal score){
      this.score = score;
      this.creditRatingList = JNConfigurations.getCreditRatings();
      this.rating = getRating(this.creditRatingList);
   }
    

   private String getRating(List<Credit_Rating__mdt> creditRatingList){
      for(Credit_Rating__mdt rating:creditRatingList){
         if(rating.Credit_Score_Min__c >= this.score && rating.Credit_Score_Max__c <= this.score){
            this.rating = rating.Rating__c;
            this.classification =  rating.Classification__c;
         }
      }
   }
}