mdapipkg/Scratch/objects/Creditor_Life_Matrix__mdt.object
<CustomObject>
    <fields>
        <fullName>X0_5__c</fullName>
        <label>0.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X10__c</fullName>
        <label>10</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1_5__c</fullName>
        <label>1.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1__c</fullName>
        <label>1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2_5__c</fullName>
        <label>2.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2__c</fullName>
        <label>2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3_5__c</fullName>
        <label>3.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3__c</fullName>
        <label>3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X4_5__c</fullName>
        <label>4.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X4__c</fullName>
        <label>4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X5_5__c</fullName>
        <label>5.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X5__c</fullName>
        <label>5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X6_5__c</fullName>
        <label>6.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X6__c</fullName>
        <label>6</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X7_5__c</fullName>
        <label>7.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X7__c</fullName>
        <label>7</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X8_5__c</fullName>
        <label>8.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X8__c</fullName>
        <label>8</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X9_5__c</fullName>
        <label>9.5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X9__c</fullName>
        <label>9</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Creditor Life Matrix</label>
    <pluralLabel>Creditor Life Matrix</pluralLabel>
</CustomObject>

force-app/main/default/classes/TestCreditorLifeMatrixWrapper.cls
/**
 * Ver  Ticket#      Date            Author                 Purpose
 * 1.0  JN1-4186     16/12/2020      Ishwari G.(thinqloud)  Test Class for CreditorLideMatrixWrapper
 **/
@isTest
public with sharing class TestCreditorLifeMatrixWrapper {
  @isTest
  public static void testWrapper1() {
    List<Creditor_Life_Matrix__mdt> creditorMatrixList = [
      SELECT
        Label,
        X0_5__c,
        X1__c,
        X1_5__c,
        X2__c,
        X2_5__c,
        X3__c,
        X3_5__c,
        X4__c,
        X4_5__c,
        X5__c,
        X5_5__c,
        X6__c,
        X6_5__c,
        X7__c,
        X7_5__c,
        X8__c,
        X8_5__c,
        X9__c,
        X9_5__c,
        X10__c
      FROM Creditor_Life_Matrix__mdt
    ];

    Test.startTest();
    CreditorLifeMatrixWrapper wrapper = new CreditorLifeMatrixWrapper(
      creditorMatrixList[0]
    );
    Decimal rating = wrapper.getCreditRating(30, 2.00);
    Test.stopTest();
  }

  @isTest
  public static void testWrapper2() {
    List<Creditor_Life_Matrix__mdt> creditorMatrixList = [
      SELECT
        Label,
        X0_5__c,
        X1__c,
        X1_5__c,
        X2__c,
        X2_5__c,
        X3__c,
        X3_5__c,
        X4__c,
        X4_5__c,
        X5__c,
        X5_5__c,
        X6__c,
        X6_5__c,
        X7__c,
        X7_5__c,
        X8__c,
        X8_5__c,
        X9__c,
        X9_5__c,
        X10__c
      FROM Creditor_Life_Matrix__mdt
    ];

    Test.startTest();
    CreditorLifeMatrixWrapper wrapper = new CreditorLifeMatrixWrapper(
      creditorMatrixList[0]
    );
    Decimal rating = wrapper.getCreditRating(46, 9.37);
    Test.stopTest();
  }
  @isTest
  public static void testWrapper3() {
    List<Creditor_Life_Matrix__mdt> creditorMatrixList = [
      SELECT
        Label,
        X0_5__c,
        X1__c,
        X1_5__c,
        X2__c,
        X2_5__c,
        X3__c,
        X3_5__c,
        X4__c,
        X4_5__c,
        X5__c,
        X5_5__c,
        X6__c,
        X6_5__c,
        X7__c,
        X7_5__c,
        X8__c,
        X8_5__c,
        X9__c,
        X9_5__c,
        X10__c
      FROM Creditor_Life_Matrix__mdt
    ];

    Test.startTest();
    CreditorLifeMatrixWrapper wrapper = new CreditorLifeMatrixWrapper(
      creditorMatrixList[0]
    );
    Decimal rating = wrapper.getCreditRating(46, 10.00);
    Test.stopTest();
  }
  @isTest
  public static void testWrapper4() {
    List<Creditor_Life_Matrix__mdt> creditorMatrixList = [
      SELECT
        Label,
        X0_5__c,
        X1__c,
        X1_5__c,
        X2__c,
        X2_5__c,
        X3__c,
        X3_5__c,
        X4__c,
        X4_5__c,
        X5__c,
        X5_5__c,
        X6__c,
        X6_5__c,
        X7__c,
        X7_5__c,
        X8__c,
        X8_5__c,
        X9__c,
        X9_5__c,
        X10__c
      FROM Creditor_Life_Matrix__mdt
    ];

    Test.startTest();
    CreditorLifeMatrixWrapper wrapper = new CreditorLifeMatrixWrapper(
      creditorMatrixList[0]
    );
    try {
      Decimal rating = wrapper.getCreditRating(46, 12.00);
    } catch (Exception e) {
      Boolean expectedExceptionThrown = e.getMessage()
          .contains(Constants.INVALID_TENURE)
        ? true
        : false;
      System.AssertEquals(expectedExceptionThrown, true);
    }

    Test.stopTest();
  }
}