mdapipkg/Scratch/objects/Credit_Rating__mdt.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Max__c</fullName>
        <label>Credit Score Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Score_Min__c</fullName>
        <label>Credit Score Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Credit Rating</label>
    <pluralLabel>Credit Rating</pluralLabel>
</CustomObject>

force-app/main/default/classes/CreditRatingWrapper.cls
/**
 * Ver  Ticket#      Date            Author                 Purpose
 * 1.0  JN1-4045     25/11/2020      Kirti R.(thinqloud)  Service class for product details component
 **/
public with sharing class CreditRatingWrapper {
  @AuraEnabled
  public String classification;
  @AuraEnabled
  public Decimal creditScoreMax;
  @AuraEnabled
  public Decimal creditScoreMin;
  @AuraEnabled
  public String rating;
  @AuraEnabled
  public String label;

  public CreditRatingWrapper(Credit_Rating__mdt creditRating) {
    this.label = creditRating.Label;
    this.classification = creditRating.Classification__c;
    this.creditScoreMax = creditRating.Credit_Score_Max__c;
    this.creditScoreMin = creditRating.Credit_Score_Min__c;
    this.rating = creditRating.Rating__c;
  }
}