mdapipkg/Scratch/objects/FinServ__Employment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_of_Business_Working_Capita__c</fullName>
        <description>Self employed persons</description>
        <label>Assessment of Business Working Capita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Adequate</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>Not Adequate</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assessment_of_Business__c</fullName>
        <description>Self employed</description>
        <label>Assessment of Business  Fin Performance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Good growth and profit trends for 3 - 4 years</fullName>
                </value>
                <value>
                    <fullName>Good growth and profit trends for up to 2 years</fullName>
                </value>
                <value>
                    <fullName>Inconsistent profit/growth trends</fullName>
                </value>
                <value>
                    <fullName>Inadequate growth and/or profit trends</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assessment_of_Statement__c</fullName>
        <label>Assessment of Business Fin Statement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Strongly Supported</fullName>
                </value>
                <value>
                    <fullName>Adequately Supported</fullName>
                </value>
                <value>
                    <fullName>Sound Business Plan, Skill and Professional Competence</fullName>
                </value>
                <value>
                    <fullName>Weak Support or Doubtful</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Industry_Category_IFRS_Self_Employed</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_of_Trade__c</fullName>
        <label>Length of Trade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>More than 5 years</fullName>
                </value>
                <value>
                    <fullName>Between 3-5 years</fullName>
                </value>
                <value>
                    <fullName>Between 1-3 years</fullName>
                </value>
                <value>
                    <fullName>Less than a 1 year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nature_of_Engagement__c</fullName>
        <label>Nature of Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Nature_of_Engagement_Self_Employed</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Professional_Category__c</fullName>
        <label>Professional Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Officer</fullName>
                </value>
                <value>
                    <fullName>Clerical</fullName>
                </value>
                <value>
                    <fullName>Skilled Worker</fullName>
                </value>
                <value>
                    <fullName>Unskilled Worker</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/FinServ__Employment__c/fields/FinServ__EmploymentStatus__c.field-meta.xml
<CustomField>
    <fullName>FinServ__EmploymentStatus__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>Contractual</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
            <value>
                <fullName>Employed</fullName>
                <isActive>false</isActive>
                <label>Employed</label>
            </value>
            <value>
                <fullName>Home Maker</fullName>
                <isActive>false</isActive>
                <label>Home Maker</label>
            </value>
            <value>
                <fullName>Pensioner</fullName>
                <isActive>false</isActive>
                <label>Pensioner</label>
            </value>
            <value>
                <fullName>Retired</fullName>
                <isActive>false</isActive>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Self-Employed</fullName>
                <isActive>false</isActive>
                <label>Self-Employed</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
            <value>
                <fullName>Unemployed with Income</fullName>
                <isActive>false</isActive>
                <label>Unemployed with Income</label>
            </value>
            <value>
                <fullName>Unemployed without Income</fullName>
                <isActive>false</isActive>
                <label>Unemployed without Income</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__Employment__c/fields/FinServ__LengthOfEmployment__c.field-meta.xml
<CustomField>
    <fullName>FinServ__LengthOfEmployment__c</fullName>
    <formula
  >If(ISBLANK(FinServ__EndDate__c),If(And(Month(TODAY())&gt;= month(FinServ__StartDate__c), Day(TODAY()) &gt;= Day(FinServ__StartDate__c)),
Year(TODAY())- Year(FinServ__StartDate__c) +
(Month(TODAY())-Month(FinServ__StartDate__c))/12,
if(And(month(TODAY())&lt; month(FinServ__StartDate__c), Day(TODAY())&gt;= Day(FinServ__StartDate__c)),
Year(TODAY())-Year(FinServ__StartDate__c)-1 +
(12 - Month(FinServ__StartDate__c)+month(TODAY()))/12,
if(And( month(TODAY())&lt; month(FinServ__StartDate__c), Day(TODAY())&lt; Day(FinServ__StartDate__c)),
(Year(TODAY())-Year(FinServ__StartDate__c)-1) + 
((12 - Month(FinServ__StartDate__c)+month(TODAY())-1))/12,
if(And( month(TODAY())= month(FinServ__StartDate__c), Day(TODAY())&lt; Day(FinServ__StartDate__c)),
(Year(TODAY())- Year(FinServ__StartDate__c)-1) + (11/12),
(Year(TODAY())- Year(FinServ__StartDate__c)) + 
(Month(TODAY())-Month(FinServ__StartDate__c)-1)/12)))),If(And(Month(FinServ__EndDate__c)&gt;= month(FinServ__StartDate__c), Day(FinServ__EndDate__c) &gt;= Day(FinServ__StartDate__c)),
Year(FinServ__EndDate__c)- Year(FinServ__StartDate__c) +
(Month(FinServ__EndDate__c)-Month(FinServ__StartDate__c))/12,
if(And(month(FinServ__EndDate__c)&lt; month(FinServ__StartDate__c), Day(FinServ__EndDate__c)&gt;= Day(FinServ__StartDate__c)),
Year(FinServ__EndDate__c)-Year(FinServ__StartDate__c)-1 +
(12 - Month(FinServ__StartDate__c)+month(FinServ__EndDate__c))/12,
if(And( month(FinServ__EndDate__c)&lt; month(FinServ__StartDate__c), Day(FinServ__EndDate__c)&lt; Day(FinServ__StartDate__c)),
(Year(FinServ__EndDate__c)-Year(FinServ__StartDate__c)-1) + 
((12 - Month(FinServ__StartDate__c)+month(FinServ__EndDate__c)-1))/12,
if(And( month(FinServ__EndDate__c)= month(FinServ__StartDate__c), Day(FinServ__EndDate__c)&lt; Day(FinServ__StartDate__c)),
(Year(FinServ__EndDate__c)- Year(FinServ__StartDate__c)-1) + (11/12),
(Year(FinServ__EndDate__c)- Year(FinServ__StartDate__c)) + 
(Month(FinServ__EndDate__c)-Month(FinServ__StartDate__c)-1)/12)))))</formula>
    <label>Length of Employment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Industry_Category_IFRS_Self_Employed.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Tourism</fullName>
    </customValue>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Retail trade</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>ICT</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <masterLabel>Industry Category - IFRS (Self-Employed)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Nature_of_Engagement_Self_Employed.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Professional service provider</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational service provider</fullName>
    </customValue>
    <customValue>
        <fullName>Trader</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Nature of Engagement (Self-Employed)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmploymentWrapper.cls
/**
 * Ver  Ticket#      Date            Author                 Purpose
 * 1.0  JN1-4045     23/11/2020      Ishwari G.(thinqloud)  Wrapper for Employment Object  
**/
public with sharing class EmploymentWrapper {

    @AuraEnabled
    public String EmploymentStatus;
    @AuraEnabled
    public String industry;
    @AuraEnabled
    public Decimal lengthOfEmployment;
    @AuraEnabled
    public String professionalCategory;
    @AuraEnabled
    public String assessmentOfBusinessWorkingCapita;
    @AuraEnabled
    public String natureOfEngagement;
    @AuraEnabled
    public String assessmentOfBusiness;
    @AuraEnabled
    public String assessmentOfStatement;
    @AuraEnabled
    public String lengthOfTrade;
    @AuraEnabled
    public String employmentType;

    public EmploymentWrapper(FinServ__Employment__c employment) {
        this.EmploymentStatus = employment.FinServ__EmploymentStatus__c;
        this.industry = employment.Industry__c;
        this.lengthOfEmployment = employment.FinServ__LengthOfEmployment__c;
        this.professionalCategory = employment.Professional_Category__c;
        this.assessmentOfBusinessWorkingCapita = employment.Assessment_of_Business_Working_Capita__c;
        this.natureOfEngagement = employment.Nature_of_Engagement__c;
        this.assessmentOfBusiness = employment.Assessment_of_Business__c;
        this.assessmentOfStatement = employment.Assessment_of_Statement__c;
        this.lengthOfTrade = employment.Length_of_Trade__c;
        this.employmentType = Schema.getGlobalDescribe().get('FinServ__Employment__c').getDescribe().getRecordTypeInfosById().get(employment.RecordTypeId).getName();
    }
}