mdapipkg/Scratch/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leads and Referrals</relationshipLabel>
        <relationshipName>Leads_and_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapipkg/Scratch/objects/Loan_Calculator__c.object
<CustomObject>
    <fields>
        <fullName>Existing_Monthly_Credit_Payment__c</fullName>
        <label>Existing Monthly Credit Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lead_and_Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead and Referral</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Loan Calculations</relationshipLabel>
        <relationshipName>Loan_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Gross_Income__c</fullName>
        <label>Monthly Gross Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Calculations</relationshipLabel>
        <relationshipName>Loan_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reqeusted_Limit__c</fullName>
        <label>Requested Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Monthly__c</fullName>
        <label>Total Monthly Loan Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Loan Calculation</label>
    <nameField>
        <displayFormat>LC-{000000000}</displayFormat>
        <label>Loan Calculator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/default/classes/TestSimpleLoanCalculationController.cls
@isTest
public class TestSimpleLoanCalculationController {
  @isTest
  public static void shouldSaveLoanCalculation() {
    Account acc = TestDataFactory.CreateBasicAccounts(1, 'hayley')[0];
    insert acc;

    Opportunity opp = TestDataFactory.CreateOpportunities(1)[0];
    opp.AccountId = acc.Id;
    insert opp;

    Lead newLead = TestDataFactory.CreateLeads(1)[0];
    insert newLead;

    Loan_Calculator__c loanCal = TestDataFactory.CreateLoanCalculation(1)[0];
    loanCal.Lead_and_Referral__c = newLead.Id;
    loanCal.Opportunity__c = opp.Id;
    loanCal.Reqeusted_Limit__c = 10000.00;
    loanCal.Interest_Rate__c = 15.0;
    loanCal.Monthly_Gross_Income__c = 3000.00;
    loanCal.Existing_Monthly_Credit_Payment__c = 500.00;
    loanCal.Total_Monthly__c = 1000.00;
    insert loanCal;

    String recordTypeName = 'InstallmentPayment';

    String Calculation = JSON.serialize(loanCal);
    System.assert(Calculation != null, 'Calculation data is null.');

    SimpleLoanCalculationController.SaveLoanCalculation(
      Calculation,
      recordTypeName
    );
  }
}