mdapipkg/Scratch/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Estimated_Amount__c</fullName>
        <label>Estimated Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_of_Interest__c</fullName>
        <label>Product of Interest</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Group_of_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>role__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapipkg/Scratch/objects/Lead_Related_Person__c.object
<CustomObject>
    <fields>
        <fullName>Afilliate_Type__c</fullName>
        <label>Afilliate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JN Bank</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Credit Card Extension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JN_Location__c</fullName>
        <label>JN Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>JN_Locations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Familial_Relationship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TItle__c</fullName>
        <description>Lead title</description>
        <label>TItle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Title</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TRN__c</fullName>
        <description>Tax registration number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>TRN</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <label>Lead Related Person</label>
    <nameField>
        <displayFormat>LRPN-{00000000}</displayFormat>
        <label>Lead Related Person Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Related Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/JN_Locations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annotto Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Barbican</fullName>
    </customValue>
    <customValue>
        <fullName>Brown&apos;s Town</fullName>
    </customValue>
    <customValue>
        <fullName>Catherine Hall</fullName>
    </customValue>
    <customValue>
        <fullName>Christiana</fullName>
    </customValue>
    <customValue>
        <fullName>Duke Street</fullName>
    </customValue>
    <customValue>
        <fullName>Falmouth</fullName>
    </customValue>
    <customValue>
        <fullName>Gayle</fullName>
    </customValue>
    <customValue>
        <fullName>Half Way Tree</fullName>
    </customValue>
    <customValue>
        <fullName>Highgate</fullName>
    </customValue>
    <customValue>
        <fullName>JN Premier</fullName>
    </customValue>
    <customValue>
        <fullName>Junction</fullName>
    </customValue>
    <customValue>
        <fullName>Linstead</fullName>
    </customValue>
    <customValue>
        <fullName>Lucea</fullName>
    </customValue>
    <customValue>
        <fullName>Mandeville</fullName>
    </customValue>
    <customValue>
        <fullName>May Pen</fullName>
    </customValue>
    <customValue>
        <fullName>Michi Supercentre</fullName>
    </customValue>
    <customValue>
        <fullName>Montego Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Morant Bay</fullName>
    </customValue>
    <customValue>
        <fullName>New Kingston</fullName>
    </customValue>
    <customValue>
        <fullName>Knutsford</fullName>
    </customValue>
    <customValue>
        <fullName>Ocho Rios</fullName>
    </customValue>
    <customValue>
        <fullName>Old Harbour</fullName>
    </customValue>
    <customValue>
        <fullName>Papine</fullName>
    </customValue>
    <customValue>
        <fullName>Port Antonio</fullName>
    </customValue>
    <customValue>
        <fullName>Port Maria</fullName>
    </customValue>
    <customValue>
        <fullName>Portmore</fullName>
    </customValue>
    <customValue>
        <fullName>Santa Cruz</fullName>
    </customValue>
    <customValue>
        <fullName>Savanna-La-Mar</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish Town</fullName>
    </customValue>
    <masterLabel>JN Locations</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Group_of_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>JN Bank Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Mortgage Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Deposit Account</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Auto Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Commercial Auto Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Line Of Credit</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Unsecured Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank 12 to 1 Loan (Supersize Loan)</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Cash Secured Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Insurance Premium Financing</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Term Share Loan</fullName>
    </customValue>
    <masterLabel>Product Group of Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/JNSiteController.cls
public class JNSiteController {
    
    @AuraEnabled
    public static List<String> getPickListValues(String objectApiName, String fieldApiName){
        List<String> pickListValuesList= new List<String>();
        Map<String , Schema.SObjectType> globalDescription = Schema.getGlobalDescribe();
        Schema.sObjectType sObjType = globalDescription.get(objectApiName);
        Schema.DescribeSObjectResult r1 = sObjType.getDescribe();
        Map<String , Schema.SObjectField> mapFieldList = r1.fields.getMap();
        
        Schema.SObjectField field = mapFieldList.get(fieldApiName);
        Schema.DescribeFieldResult fieldResult = field.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        } 
        return pickListValuesList;
    }
    @AuraEnabled
    public static Map<String, List<String>> getPickListValuesList(String objectApiName, List<String> fieldApiNames){
        List<String> pickListValuesList= new List<String>();
        Map<String, List<String>> mapFields = new Map<String, List<String>>();
        
        Map<String , Schema.SObjectType> globalDescription = Schema.getGlobalDescribe();
        Schema.sObjectType sObjType = globalDescription.get(objectApiName);
        Schema.DescribeSObjectResult r1 = sObjType.getDescribe();
        Map<String , Schema.SObjectField> mapFieldList = r1.fields.getMap();
        
        for(String fieldApiName: fieldApiNames){
            Schema.SObjectField field = mapFieldList.get(fieldApiName);
            Schema.DescribeFieldResult fieldResult = field.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            pickListValuesList = new List<String>();
            for( Schema.PicklistEntry pickListVal : ple){
                pickListValuesList.add(pickListVal.getLabel());
            } 
            mapFields.put(fieldApiName, pickListValuesList);
        }
        
        return mapFields;
    }
    @AuraEnabled
    public static Lead createLeadReferral(String firstName, String lastName, String serviceofInterest,Decimal estimatedAmount ){
        List<Lead> leads = [SELECT Id FROM Lead WHERE  LastName = :lastName AND LastName = :lastName];
        if(leads.isEmpty()){
            Lead newLead = new Lead(FirstName=firstName, LastName=lastName, 
                                    Estimated_Amount__c=estimatedAmount, Service_of_Interest__c =serviceofInterest);
            insert newLead;
            return newLead;
        } else {
            // lead already exist
            throw new AuraHandledException('A lead with the entered first and last name already exists');
        }
        
    }
    @AuraEnabled
    public static Object createPersonAffiliates(Map<String, Object> values , String leadId){
        try {
            
            List<Lead_Related_Person__c> persons = new List<Lead_Related_Person__c>();
            Map<String, Object>  oldPerson;
            for (String key : values.keySet()) {
                String c = JSON.serialize(values.get(key));
                oldPerson = (Map<String, Object>) JSON.deserializeUntyped(c);
                Lead_Related_Person__c newPerson = new Lead_Related_Person__c();
                
                newPerson.First_Name__c = String.valueOf(oldPerson.get('First_Name__c'));
                newPerson.Last_Name__c = String.valueOf(oldPerson.get('Last_Name__c'));
                newPerson.Role__c = String.valueOf(oldPerson.get('Role__c'));
                newPerson.Relationship__c = String.valueOf(oldPerson.get('Relationship__c')); 
                newPerson.Afilliate_Type__c = String.valueOf(oldPerson.get('Afilliate_Type__c'));
                newPerson.JN_Location__c  = String.valueOf(oldPerson.get('JN_Location__c'));
                persons.add(newPerson);
            }
            if(!persons.isEmpty()){
                insert persons;
            }            
            return persons;
        } catch(Exception e){
            return e;
        }
    }
    @AuraEnabled
    public static Object createPersonExtensions(Map<String, Object> values , String leadId){
        try {
            
            List<Lead_Related_Person__c> persons = new List<Lead_Related_Person__c>();
            Map<String, Object>  oldPerson;
            for (String key : values.keySet()) {
                String c = JSON.serialize(values.get(key));
                oldPerson = (Map<String, Object>) JSON.deserializeUntyped(c);
                Lead_Related_Person__c newPerson = new Lead_Related_Person__c();
                
                newPerson.First_Name__c = String.valueOf(oldPerson.get('First_Name__c'));
                newPerson.Last_Name__c = String.valueOf(oldPerson.get('Last_Name__c'));
                newPerson.Middle_Name__c = String.valueOf(oldPerson.get('Middle_Name__c'));
                newPerson.Title__c = String.valueOf(oldPerson.get('Title__c'));
                newPerson.Relationship__c = String.valueOf(oldPerson.get('Relationship__c')); 
                newPerson.TRN__c = Decimal.valueOf(String.valueOf(oldPerson.get('TRN__c')));
                newPerson.Afilliate_Type__c = String.valueOf(oldPerson.get('Afilliate_Type__c'));
                
                persons.add(newPerson);
            }
            if(!persons.isEmpty()){
                insert persons;
            }            
            return persons;
        } catch(Exception e){
            return e;
        }
    }
    @AuraEnabled
    public static Object saveFile(Id parentId, String fileName, String base64Data, String contentType) {
        ContentVersion conVer = new ContentVersion();
        try {
            String extension = fileName.substring(fileName.lastIndexOf('.')+1);
            String name = fileName.substring(0, fileName.lastIndexOf('.'));
            conVer.ContentLocation = 'S'; // S specify this document is in SF, use E for external files
            conVer.PathOnClient = fileName; // The files name, extension is very important here which will help the file in preview.
            conVer.Title = name; // Display name of the files
            conVer.VersionData = EncodingUtil.base64Decode(base64Data); // converting your binary string to Blog
            insert conVer;
            
            // First get the content document Id from ContentVersion
            List<ContentVersion> contentVersions = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id];
            if(!contentVersions.isEmpty()){
                Id conDoc = contentVersions.get(0).ContentDocumentId;
                //Create ContentDocumentLink
                ContentDocumentLink cDe = new ContentDocumentLink();
                cDe.ContentDocumentId = conDoc;
                cDe.LinkedEntityId = parentId; // you can use objectId,GroupId etc
                cDe.ShareType = 'I'; // Inferred permission, checkout description of ContentDocumentLink object for more details
                
                insert cDe;
                return cDe.Id;
            } 
            return null;
            
        } catch(Exception e) {
            System.debug(e);
            
            return e;
        }
    }
    @AuraEnabled
    public static Object updateLeadInformation(Map<String, String> currentLead){
        try {
            Id leadId = currentLead.get('Id');
            Lead foundLead = [SELECT Id FROM Lead WHERE Id =:leadId];
            if(foundLead != null) {
                for(String field: currentLead.keySet()){
                    foundLead.put(field, currentLead.get(field));
                }
            }
            update foundLead;
            return foundLead;
        } catch(Exception e){
            return e;
        }
    }
}