mdapipkg/Scratch/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Country_of_Citizenship__c</fullName>
        <label>Country of Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FinServ__Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <label>Country of Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FinServ__Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Amount__c</fullName>
        <label>Estimated Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gross_Monthly_Expenses__c</fullName>
        <description>Unsecured Loan form</description>
        <label>Gross Monthly Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Monthly_Income__c</fullName>
        <label>Gross Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Highest_Level_of_Education_Attained__c</fullName>
        <label>Highest Level of Education Attained</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Education</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Jamaican_Tax_Registration_Number__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Jamaican Tax Registration Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose_UL__c</fullName>
        <label>Loan Purpose (UL)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Loan_Purpose_Unsecured</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Marital_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mother_s_Maiden_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Mother&apos;s Maiden Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Dependent_Adults__c</fullName>
        <label>Number of Dependent Adults</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Dependent_Children__c</fullName>
        <label>Number of Dependent Children</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Place_of_Birth__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Place of Birth</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Date_of_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferred Date of Contact</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preferred_Location__c</fullName>
        <label>Preferred Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>JN_Locations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Time_of_Contact__c</fullName>
        <label>Preferred Time of Contact</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Service_of_Interest__c</fullName>
        <label>Product of Interest</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Group_of_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>role__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapipkg/Scratch/objects/Lead_Related_Person__c.object
<CustomObject>
    <fields>
        <fullName>Afilliate_Type__c</fullName>
        <label>Afilliate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JN Bank</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Credit Card Extension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_and_Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead and Referral</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Lead Related Persons</relationshipLabel>
        <relationshipName>Lead_Related_Persons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Familial_Relationship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TItle__c</fullName>
        <description>Lead title</description>
        <label>TItle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Title</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TRN__c</fullName>
        <description>Tax registration number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>TRN</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <label>Lead Related Person</label>
    <nameField>
        <displayFormat>LRPN-{00000000}</displayFormat>
        <label>Lead Related Person Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Related Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/Scratch/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gross_Monthly_Income__c</fullName>
        <label>Gross Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jamaican_Tax_Registration_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Jamaican Tax Registration Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Location__c</fullName>
        <label>Preferred Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>JN_Locations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Title</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapipkg/Scratch/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>TEXT(PricebookEntry.Product2.Family)</formula>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Education.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Basic</fullName>
    </customValue>
    <customValue>
        <fullName>Primary</fullName>
    </customValue>
    <customValue>
        <fullName>High School</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher Training Colleges</fullName>
    </customValue>
    <customValue>
        <fullName>Community Colleges</fullName>
    </customValue>
    <customValue>
        <fullName>Other College/Institutions</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Post Graduate</fullName>
    </customValue>
    <masterLabel>Education</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/JN_Locations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annotto Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Barbican</fullName>
    </customValue>
    <customValue>
        <fullName>Brown&apos;s Town</fullName>
    </customValue>
    <customValue>
        <fullName>Catherine Hall</fullName>
    </customValue>
    <customValue>
        <fullName>Christiana</fullName>
    </customValue>
    <customValue>
        <fullName>Duke Street</fullName>
    </customValue>
    <customValue>
        <fullName>Falmouth</fullName>
    </customValue>
    <customValue>
        <fullName>Gayle</fullName>
    </customValue>
    <customValue>
        <fullName>Half Way Tree</fullName>
    </customValue>
    <customValue>
        <fullName>Highgate</fullName>
    </customValue>
    <customValue>
        <fullName>JN Premier</fullName>
    </customValue>
    <customValue>
        <fullName>Junction</fullName>
    </customValue>
    <customValue>
        <fullName>Linstead</fullName>
    </customValue>
    <customValue>
        <fullName>Lucea</fullName>
    </customValue>
    <customValue>
        <fullName>Mandeville</fullName>
    </customValue>
    <customValue>
        <fullName>May Pen</fullName>
    </customValue>
    <customValue>
        <fullName>Michi Supercentre</fullName>
    </customValue>
    <customValue>
        <fullName>Montego Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Morant Bay</fullName>
    </customValue>
    <customValue>
        <fullName>New Kingston</fullName>
    </customValue>
    <customValue>
        <fullName>Knutsford</fullName>
    </customValue>
    <customValue>
        <fullName>Ocho Rios</fullName>
    </customValue>
    <customValue>
        <fullName>Old Harbour</fullName>
    </customValue>
    <customValue>
        <fullName>Papine</fullName>
    </customValue>
    <customValue>
        <fullName>Port Antonio</fullName>
    </customValue>
    <customValue>
        <fullName>Port Maria</fullName>
    </customValue>
    <customValue>
        <fullName>Portmore</fullName>
    </customValue>
    <customValue>
        <fullName>Santa Cruz</fullName>
    </customValue>
    <customValue>
        <fullName>Savanna-La-Mar</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish Town</fullName>
    </customValue>
    <masterLabel>JN Locations</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Loan_Purpose_Unsecured.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Purchase of Motor Vehicle</fullName>
    </customValue>
    <customValue>
        <fullName>Refinance of Motor Vehicle</fullName>
    </customValue>
    <customValue>
        <fullName>Equity</fullName>
    </customValue>
    <masterLabel>Loan Purpose (Unsecured)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Marital_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Married</fullName>
    </customValue>
    <customValue>
        <fullName>Common Law</fullName>
    </customValue>
    <customValue>
        <fullName>Widowed</fullName>
    </customValue>
    <customValue>
        <fullName>Separated</fullName>
    </customValue>
    <customValue>
        <fullName>Divorced</fullName>
    </customValue>
    <customValue>
        <fullName>Not Married</fullName>
    </customValue>
    <masterLabel>Marital Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Group_of_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>JN Bank Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Mortgage Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Deposit Account</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Auto Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Commercial Auto Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Line Of Credit</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Unsecured Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank 12 to 1 Loan (Supersize Loan)</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Cash Secured Loan</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Insurance Premium Financing</fullName>
    </customValue>
    <customValue>
        <fullName>JN Bank Term Share Loan</fullName>
    </customValue>
    <masterLabel>Product Group of Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Wrappers.cls
public with sharing class Wrappers {
  /**
   * throws a null pointer exception with custom message
   * @param {String} - msg exception text
   * @return Void
   */
  public static void throwNullException(String msg) {
    NullPointerException error = new NullPointerException();
    error.setMessage(msg);
    throw error;
  }

  /**
   * Used for serializing a Lead
   * @constructor LeadWrapper
   */
  public class LeadWrapper {
    @AuraEnabled
    public String leadId;
    @AuraEnabled
    public String leadSource;
    @AuraEnabled
    public String firstName;
    @AuraEnabled
    public String lastName;
    @AuraEnabled
    public Decimal estimatedAmount;
    @AuraEnabled
    public String serviceOfInterest;
    @AuraEnabled
    public String salutation;
    @AuraEnabled
    public String middleName;
    @AuraEnabled
    public String suffix;
    @AuraEnabled
    public String gender;
    @AuraEnabled
    public String maritalStatus;
    @AuraEnabled
    public Date dob;
    @AuraEnabled
    public String birthPlace;
    @AuraEnabled
    public String maidenName;
    @AuraEnabled
    public Decimal dependentAdultNum;
    @AuraEnabled
    public Decimal dependentChildNum;
    @AuraEnabled
    public String citizenCountry;
    @AuraEnabled
    public String residentCountry;
    @AuraEnabled
    public String educationLevel;
    @AuraEnabled
    public String trn;
    @AuraEnabled
    public Date preferredContactDate;
    @AuraEnabled
    public Time preferredContactTime;
    @AuraEnabled
    public String preferredLocation;
    @AuraEnabled
    public String loanPurposeUL;
    @AuraEnabled
    public Decimal grossMonthlyIncome;
    @AuraEnabled
    public Decimal grossMonthlyExpenses;
    @AuraEnabled
    public Id recordTypeId;

    public LeadWrapper(Lead record) {
      if (record == null) {
        Wrappers.throwNullException('Lead record cannot be null');
      }
      this.leadId = record.Id;
      this.leadSource = record.LeadSource;
      this.firstName = record.FirstName;
      this.lastName = record.LastName;
      this.estimatedAmount = record.Estimated_Amount__c;
      this.serviceOfInterest = record.Service_of_Interest__c;
      this.salutation = record.Salutation;
      this.middleName = record.MiddleName;
      this.suffix = record.Suffix;
      this.gender = record.Gender__c;
      this.maritalStatus = record.Marital_Status__c;
      this.dob = record.Date_of_Birth__c;
      this.birthPlace = record.Place_of_Birth__c;
      this.maidenName = record.Mother_s_Maiden_Name__c;
      this.dependentAdultNum = record.Number_of_Dependent_Adults__c;
      this.dependentChildNum = record.Number_of_Dependent_Children__c;
      this.citizenCountry = record.Country_of_Citizenship__c;
      this.residentCountry = record.Country_of_Residence__c;
      this.educationLevel = record.Highest_Level_of_Education_Attained__c;
      this.trn = record.Jamaican_Tax_Registration_Number__c;
      this.preferredContactDate = record.Preferred_Date_of_Contact__c;
      this.preferredContactTime = record.Preferred_Time_of_Contact__c;
      this.preferredLocation = record.Preferred_Location__c;
      this.loanPurposeUL = record.Loan_Purpose_UL__c;
      this.grossMonthlyIncome = record.Gross_Monthly_Income__c;
      this.grossMonthlyExpenses = record.Gross_Monthly_Expenses__c;
      this.recordTypeId = record.RecordTypeId;
    }
  }
  /**
   * Used for deserializing a Lead
   * @constructor LeadUnwrapper
   */
  public class LeadUnwrapper {
    @AuraEnabled
    public String leadId;
    @AuraEnabled
    public String leadSource;
    @AuraEnabled
    public String firstName;
    @AuraEnabled
    public String lastName;
    @AuraEnabled
    public Decimal estimatedAmount;
    @AuraEnabled
    public String serviceOfInterest;
    @AuraEnabled
    public String salutation;
    @AuraEnabled
    public String middleName;
    @AuraEnabled
    public String suffix;
    @AuraEnabled
    public String gender;
    @AuraEnabled
    public String maritalStatus;
    @AuraEnabled
    public Date dob;
    @AuraEnabled
    public String birthPlace;
    @AuraEnabled
    public String maidenName;
    @AuraEnabled
    public Decimal dependentAdultNum;
    @AuraEnabled
    public Decimal dependentChildNum;
    @AuraEnabled
    public String citizenCountry;
    @AuraEnabled
    public String residentCountry;
    @AuraEnabled
    public String educationLevel;
    @AuraEnabled
    public String trn;
    @AuraEnabled
    public Date preferredContactDate;
    @AuraEnabled
    public Time preferredContactTime;
    @AuraEnabled
    public String preferredLocation;
    @AuraEnabled
    public String loanPurposeUL;
    @AuraEnabled
    public Decimal grossMonthlyIncome;
    @AuraEnabled
    public Decimal grossMonthlyExpenses;
    @AuraEnabled
    public Id recordTypeId;
    @AuraEnabled
    public Lead lead;

    public LeadUnwrapper(LeadWrapper leadWrapper) {
      if (leadWrapper == null) {
        Wrappers.throwNullException('LeadWrapper record cannot be null');
      }
      this.lead = new Lead();
      this.lead.Id = leadWrapper.leadId;
      this.lead.LeadSource = leadWrapper.leadSource;
      this.lead.FirstName = leadWrapper.firstName;
      this.lead.LastName = leadWrapper.lastName;
      this.lead.Estimated_Amount__c = leadWrapper.estimatedAmount;
      this.lead.Service_of_Interest__c = leadWrapper.serviceOfInterest;
      this.lead.Salutation = leadWrapper.salutation;
      this.lead.MiddleName = leadWrapper.middleName;
      this.lead.Suffix = leadWrapper.suffix;
      this.lead.Gender__c = leadWrapper.gender;
      this.lead.Marital_Status__c = leadWrapper.maritalStatus;
      this.lead.Date_of_Birth__c = leadWrapper.dob;
      this.lead.Place_of_Birth__c = leadWrapper.birthPlace;
      this.lead.Mother_s_Maiden_Name__c = leadWrapper.maidenName;
      this.lead.Number_of_Dependent_Adults__c = leadWrapper.dependentAdultNum;
      this.lead.Number_of_Dependent_Children__c = leadWrapper.dependentChildNum;
      this.lead.Country_of_Citizenship__c = leadWrapper.citizenCountry;
      this.lead.Country_of_Residence__c = leadWrapper.residentCountry;
      this.lead.Highest_Level_of_Education_Attained__c = leadWrapper.educationLevel;
      this.lead.Jamaican_Tax_Registration_Number__c = leadWrapper.trn;
      this.lead.Preferred_Date_of_Contact__c = leadWrapper.preferredContactDate;
      this.lead.Preferred_Time_of_Contact__c = leadWrapper.preferredContactTime;
      this.lead.Preferred_Location__c = leadWrapper.preferredLocation;
      this.lead.Loan_Purpose_UL__c = leadWrapper.loanPurposeUL;
      this.lead.Gross_Monthly_Income__c = leadWrapper.grossMonthlyIncome;
      this.lead.Gross_Monthly_Expenses__c = leadWrapper.grossMonthlyExpenses;
      this.lead.RecordTypeId = leadWrapper.recordTypeId;
    }
  }

  /**
   * Used for serializing a LeadRelatedPerson
   * @constructor LeadRelatedPersonWrapper
   */
  public class LeadRelatedPersonWrapper {
    @AuraEnabled
    public String leadRelatedPersonId;
    @AuraEnabled
    public String title;
    @AuraEnabled
    public String firstName;
    @AuraEnabled
    public String middleName;
    @AuraEnabled
    public String lastName;
    @AuraEnabled
    public String trn;
    @AuraEnabled
    public String role;
    @AuraEnabled
    public String relationship;
    @AuraEnabled
    public String affiliateType;
    @AuraEnabled
    public String leadId;
    @AuraEnabled
    public String mobileNumber;

    public LeadRelatedPersonWrapper(Lead_Related_Person__c record) {
      if (record == null) {
        Wrappers.throwNullException(
          'Lead Related Person record cannot be null'
        );
      }
      this.leadRelatedPersonId = record.Id;
      this.firstName = record.First_Name__c;
      this.lastName = record.Last_Name__c;
      this.trn = record.TRN__c;
      this.role = record.Role__c;
      this.relationship = record.Relationship__c;
      this.affiliateType = record.Afilliate_Type__c;
      this.leadId = record.Lead_and_Referral__c;
      this.title = record.Title__c;
      this.middleName = record.Middle_Name__c;
      this.mobileNumber = record.Mobile_Number__c;
    }
  }
  /**
   * Used for wrapping a Opportunity Product
   * @constructor ProductSelectionWrapper
   */
  public class ProductSelectionWrapper {
    @AuraEnabled
    public String productFamily;
    @AuraEnabled
    public String productName;
    @AuraEnabled
    public Decimal productPrice;

    public ProductSelectionWrapper(OpportunityLineItem record) {
      if (record == null) {
        Wrappers.throwNullException(
          'OpportunityLineItem record cannot be null'
        );
      }
      this.productFamily = record.Product_Family__c;
      this.productName = record.Name;
      this.productPrice = record.UnitPrice;
    }
  }
}