mdapipkg/Scratch/objects/Loan_Calculator__c.object
<CustomObject>
    <fields>
        <fullName>Ability_to_Service_CC__c</fullName>
        <label>Ability to Service CC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Repayment_Method_CC__c</fullName>
        <label>Repayment Method CC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Repayment_Method</valueSetName>
        </valueSet>
    </fields>
    <label>Loan Calculation</label>
    <nameField>
        <displayFormat>LC-{000000000}</displayFormat>
        <label>Loan Calculator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Repayment_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salary Deduction</fullName>
    </customValue>
    <customValue>
        <fullName>Standing Order</fullName>
    </customValue>
    <customValue>
        <fullName>Over The Counter</fullName>
    </customValue>
    <masterLabel>Repayment Method</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LoanCalculationsWrapper.cls
/**
 * Ver  Ticket#      Date            Author                 Purpose
 * 1.0  JN1-4045     23/11/2020      Ishwari G.(thinqloud)  Wrapper For Loan Calculations
 **/
public with sharing class LoanCalculationsWrapper {
  @AuraEnabled
  public String repaymentMethod;
  @AuraEnabled
  public Decimal abilityToServiceCC;

  public LoanCalculationsWrapper(Loan_Calculator__c loanCalculations) {
    this.repaymentMethod = loanCalculations.Repayment_Method_CC__c;
    this.abilityToServiceCC = loanCalculations.Ability_to_Service_CC__c;
  }
}