mdapipkg/Scratch/objects/Loan_Calculator__c.object
<CustomObject>
    <fields>
        <fullName>Account_Holders__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Holders</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Annual_Interest_Rate_on_Deposit_Account__c</fullName>
        <label>Annual Interest Rate on Deposit Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Coverage_Type__c</fullName>
        <label>Coverage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applicant 1 Only</fullName>
                </value>
                <value>
                    <fullName>No Suitable Applicants</fullName>
                </value>
                <value>
                    <fullName>Applicant 2 Only</fullName>
                </value>
                <value>
                    <fullName>Applicant 3 Only</fullName>
                </value>
                <value>
                    <fullName>Applicant 1 &amp; Applicant 2</fullName>
                </value>
                <value>
                    <fullName>Applicant 1 &amp; Applicant 3</fullName>
                </value>
                <value>
                    <fullName>Applicant 2 &amp; Applicant 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financial_Institution__c</fullName>
        <label>Financial Institution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Financial_Institution_Secured_Line</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_in_programme__c</fullName>
        <label>Interested in programme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JNGI_Motor_Premium_1st_Year__c</fullName>
        <description>During Moratorium</description>
        <label>JNGI Motor Premium (1st Year) during</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Premium__c</fullName>
        <description>This the JNGI Premium</description>
        <label>Monthly Premium JNGI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name_of_Insurance_Provider__c</fullName>
        <label>Name of Insurance Provider</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sagicor</fullName>
                </value>
                <value>
                    <fullName>Guardian Life</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Loan Calculations</relationshipLabel>
        <relationshipName>Loan_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stamp_Duty__c</fullName>
        <label>Stamp Duty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Card__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Type of Card</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Loan Calculation</label>
    <nameField>
        <displayFormat>LC-{000000000}</displayFormat>
        <label>Loan Calculator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculations</pluralLabel>
    <recordTypes>
        <fullName>Product_Details</fullName>
        <active>true</active>
        <label>Product Details</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculator__c/fields/Creditor_Life_Denial_Reason_Text__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Life_Denial_Reason_Text__c</fullName>
    <description>Creditor Life Denial Reason</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Creditor Life Denial Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Calculator__c/fields/Deposit_Account_Balance_Number__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account_Balance_Number__c</fullName>
    <description>Deposit Account Balance</description>
    <label>Deposit Account Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculator__c/fields/Deposit_Account_Number_Text__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account_Number_Text__c</fullName>
    <description>Deposit Account Number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Deposit Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Calculator__c/fields/Estimated_Stamp_Duty_AdminCharges_Number__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Stamp_Duty_AdminCharges_Number__c</fullName>
    <label>Estimated Stamp Duty &amp; Admin Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Calculator__c/fields/Hypothecated_Loan_Flag__c.field-meta.xml
<CustomField>
    <fullName>Hypothecated_Loan_Flag__c</fullName>
    <description>hypothecated</description>
    <label>Hypothecated Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculator__c/fields/Life_Insurance_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Life_Insurance_Coverage__c</fullName>
    <description>Life Insurance Coverage</description>
    <label>Life Insurance Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Life and Critical Illness Protection</fullName>
            </value>
            <value>
                <fullName>Life Protection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanCalculationUnwrapper.cls
/**
 * @description       :
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             :
 * @last modified on  : 03-02-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log
 * Ver   Date         Author                               Modification
 * 1.0   02-26-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
 **/
public class LoanCalculationUnwrapper {
  private static final String TAG = 'LoanCalculationUnwrapper';
  @AuraEnabled
  public Loan_Calculator__c record;
  public LoanCalculationUnwrapper(ProductDetailsSerializer serializer) {
    this.record = new Loan_Calculator__c();
    record.Loan_Amount__c = serializer.loanAmount;
    record.Interested_in_programme__c = serializer.interestedInPremiumFlag;
    record.Monthly_Premium__c = serializer.jngiMonthlyPremium;
    //record.Coverage_Type__c = serializer.coverageType;
    record.Type_of_Card__c = serializer.cardType;
    record.JNGI_Motor_Premium_1st_Year__c = serializer.jngiMotorPremium;
    record.Estimated_Stamp_Duty_AdminCharges_Number__c = serializer.stampDutyAndAdminCharges;
    //record.Stamp_Duty__c = serializer.stampDuty;
    record.Creditor_Life_Denial_Reason_Text__c = serializer.noCreditorLifeReason;
    record.Name_of_Insurance_Provider__c = serializer.policyProvider;
    record.Type_of_Card__c = serializer.cardType;
    record.Financial_Institution__c = serializer.financialInstitution;
    //record.Deposit_Account_Number_Text__c = serializer.depositAccountNumber;
    record.Account_Holders__c = serializer.accountHolder;
    record.Annual_Interest_Rate_on_Deposit_Account__c = serializer.annualInterestRate;
    record.Hypothecated_Loan_Flag__c = serializer.hypothecatedLoan;
    record.Deposit_Account_Balance_Number__c = serializer.depositBalance;
    record.Life_Insurance_Coverage__c = serializer.lifeInsuranceCoverage;
  }
  /**
   * save loan calculations oject
   * @param {Id} opportunityId
   * @return {Id}
   */
  public Id save(Id opportunityId) {
    try {
      Map<String, Id> recordTypeIds = Util.getRecordTypeids(
        'Loan_Calculator__c'
      );
      this.record.RecordTypeId = recordTypeIds.get('Product_Details');
      this.record.Opportunity__c = opportunityId;
      insert this.record;
      return this.record.Id;
    } catch (Exception e) {
      System.debug(TAG + ' ' + e.getMessage());
      throw new StringException(e.getMessage());
    }
  }
}