force-app/main/default/objects/JN_Defaults__mdt/JN_Defaults__mdt.object-meta.xml
<CustomObject>
    <description>custom meta data type to represent all the JN defaults.</description>
    <label>JN Defaults</label>
    <pluralLabel>JN Defaults</pluralLabel>
</CustomObject>

force-app/main/default/objects/JN_Defaults__mdt/fields/Assignment_Fee__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Fee__c</fullName>
    <defaultValue>4538.63</defaultValue>
    <label>Assignment Fee</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/Classic_Card_Fee__c.field-meta.xml
<CustomField>
    <fullName>Classic_Card_Fee__c</fullName>
    <label>Classic Card Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/Estimated_Stamp_Duty_Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Stamp_Duty_Admin_Fee__c</fullName>
    <defaultValue>8000.00</defaultValue>
    <label>Estimated Stamp Duty &amp; Admin Fee</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/GCT__c.field-meta.xml
<CustomField>
    <fullName>GCT__c</fullName>
    <label>GCT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/Gold_Card_Fee__c.field-meta.xml
<CustomField>
    <fullName>Gold_Card_Fee__c</fullName>
    <label>Gold Card Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/Legal_Fee__c.field-meta.xml
<CustomField>
    <fullName>Legal_Fee__c</fullName>
    <defaultValue>1000</defaultValue>
    <label>Legal Fee</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/LOC_Credit_Limit_Percent__c.field-meta.xml
<CustomField>
    <fullName>LOC_Credit_Limit_Percent__c</fullName>
    <label>LOC Credit Limit Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/NSIPP_Registration_Fee__c.field-meta.xml
<CustomField>
    <fullName>NSIPP_Registration_Fee__c</fullName>
    <defaultValue>1000</defaultValue>
    <label>NSIPP Registration Fee</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Policy_Limit__c</fullName>
    <label>Policy Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/Stamp_Duty_Auto__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty_Auto__c</fullName>
    <defaultValue>530</defaultValue>
    <label>Stamp Duty for Auto Loans</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/Stamp_Duty_Uns__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty_Uns__c</fullName>
    <defaultValue>20</defaultValue>
    <label>Stamp Duty for Unsecured Loans</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JN_Defaults__mdt/fields/Supplementary_Card_Fee__c.field-meta.xml
<CustomField>
    <fullName>Supplementary_Card_Fee__c</fullName>
    <label>Supplementary Card Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/JNConfiguration.cls
/**
 * Ver  Ticket#      Date            Author                 Purpose
 * 1.0  JN1-3969     4/12/2020      Ishwari G.(thinqloud)  Added new fields in the wrapper
 **/
public class JNConfiguration {
  @AuraEnabled
  public Decimal gct;
  @AuraEnabled
  public Decimal assignmentFee;
  @AuraEnabled
  public Decimal estimatedStampDutyAndAdminFee;
  @AuraEnabled
  public Decimal legalFee;
  @AuraEnabled
  public Decimal stampDutyUns;
  @AuraEnabled
  public Decimal stampDutyAuto;
  @AuraEnabled
  public Decimal nsipp;
  @AuraEnabled
  public Decimal policyLimit;
  //JN1-3969
  @AuraEnabled
  public Decimal goldCardFee;
  //JN1-3969
  @AuraEnabled
  public Decimal classicCardFee;
  //JN1-3969
  @AuraEnabled
  public Decimal supplementaryCardFee;
  //JN1-3969
  @AuraEnabled
  public Decimal locCreditLimitPercent;
  public JNConfiguration(JN_Defaults__mdt record) {
    this.gct = record.GCT__c;
    this.assignmentFee =
      record.Assignment_Fee__c + (record.Assignment_Fee__c * record.GCT__c);
    this.estimatedStampDutyAndAdminFee = record.Estimated_Stamp_Duty_Admin_Fee__c;
    this.legalFee = record.Legal_Fee__c + (record.Legal_Fee__c * record.GCT__c);
    this.stampDutyUns = record.Stamp_Duty_Uns__c;
    this.stampDutyAuto = record.Stamp_Duty_Auto__c;
    this.nsipp = record.NSIPP_Registration_Fee__c;
    this.policyLimit = record.Policy_Limit__c;
    this.goldCardFee = record.Gold_Card_Fee__c; //JN1-3969
    this.classicCardFee = record.Classic_Card_Fee__c; //JN1-3969
    this.supplementaryCardFee = record.Supplementary_Card_Fee__c; //JN1-3969
    this.locCreditLimitPercent = record.LOC_Credit_Limit_Percent__c; //JN1-3969
  }
}