force-app/main/default/objects/Personal_Credit_Score_Model__mdt/Personal_Credit_Score_Model__mdt.object-meta.xml
<CustomObject>
    <description>Used to represent the credit calculations for JN.</description>
    <label>Personal Credit Score Model</label>
    <pluralLabel>Personal Credit Score Model</pluralLabel>
</CustomObject>

force-app/main/default/objects/Personal_Credit_Score_Model__mdt/fields/Salaried_Score_Number__c.field-meta.xml
<CustomField>
    <fullName>Salaried_Score_Number__c</fullName>
    <label>Salaried Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Personal_Credit_Score_Model__mdt/fields/Self_Employed_Score_Number__c.field-meta.xml
<CustomField>
    <fullName>Self_Employed_Score_Number__c</fullName>
    <label>Self Employed Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Personal_Credit_Score_Model__mdt/fields/Sub_Criteria_Option__c.field-meta.xml
<CustomField>
    <fullName>Sub_Criteria_Option__c</fullName>
    <label>Sub Criteria Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personal_Credit_Score_Model__mdt/fields/Sub_Criteria_Options__c.field-meta.xml
<CustomField>
    <fullName>Sub_Criteria_Options__c</fullName>
    <label>Sub Criteria Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;1 year</fullName>
                <default>true</default>
                <label>&lt;1 year</label>
            </value>
            <value>
                <fullName>&lt;60%</fullName>
            </value>
            <value>
                <fullName>&gt;3 years</fullName>
            </value>
            <value>
                <fullName>&gt;5 years</fullName>
            </value>
            <value>
                <fullName>&gt;95%</fullName>
            </value>
            <value>
                <fullName>1 - 10 days Delinquent</fullName>
            </value>
            <value>
                <fullName>11 - 30 days Delinquent</fullName>
            </value>
            <value>
                <fullName>1-3 years</fullName>
            </value>
            <value>
                <fullName>31 - 60 days Delinquent</fullName>
            </value>
            <value>
                <fullName>4-5 years</fullName>
            </value>
            <value>
                <fullName>61%-85%</fullName>
            </value>
            <value>
                <fullName>61 - 90 days Delinquent</fullName>
            </value>
            <value>
                <fullName>86%-90%</fullName>
            </value>
            <value>
                <fullName>91%-95%</fullName>
            </value>
            <value>
                <fullName>Adequate</fullName>
            </value>
            <value>
                <fullName>Adequately Supported</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Clerical</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Good growth and or profit trends for 3 - 4 years</fullName>
            </value>
            <value>
                <fullName>Good growth and or profit trends for up to 2 years</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>High School</fullName>
            </value>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>Inadequate growth and or profit trends</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Personal_Credit_Score_Model__mdt/fields/Sub_Criteria_Weight_Numbr__c.field-meta.xml
<CustomField>
    <fullName>Sub_Criteria_Weight_Numbr__c</fullName>
    <label>Sub Criteria Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Personal_Credit_Score_Model__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PersonalCreditScoreModelWrapper.cls
/**
 * Ver  Ticket#      Date            Author                 Purpose
 * 1.0  JN1-4045     24/11/2020      Ishwari G.(thinqloud)  Wrapper for PersonalCreditScoreModel Metadata  
**/
public class PersonalCreditScoreModelWrapper {
    
    @AuraEnabled
    public String subCriteriaOption;
    @AuraEnabled
    public Decimal salariedScore;
    @AuraEnabled
    public String type;
    @AuraEnabled
    public String subCriteriaOptions;
    @AuraEnabled
    public Decimal selfEmployedScore;
    @AuraEnabled
    public Decimal subCriteriaWeight;
    @AuraEnabled
    public String label;
    
    public PersonalCreditScoreModelWrapper(Personal_Credit_Score_Model__mdt personalCreditModel){
        this.label = personalCreditModel.MasterLabel;
        this.subCriteriaOption = personalCreditModel.Sub_Criteria_Option__c;
        this.salariedScore = personalCreditModel.Salaried_Score_Number__c;
        this.type = personalCreditModel.Type__c;
        this.subCriteriaOptions = personalCreditModel.Sub_Criteria_Options__c;
        this.selfEmployedScore = personalCreditModel.Self_Employed_Score_Number__c;
        this.subCriteriaWeight = personalCreditModel.Sub_Criteria_Weight_Numbr__c;
    }

}