force-app/main/default/objects/OneJN_Event_Log__c/OneJN_Event_Log__c.object-meta.xml
<CustomObject>
    <description>stores all platform events related to one jn.</description>
    <label>OneJN Event Log</label>
    <nameField>
        <displayFormat>OJE-{0000}</displayFormat>
        <label>OneJN Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OneJN Events Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OneJN_Event_Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Payload</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OneJN_Event_Log__c/fields/Event_Source__c.field-meta.xml
<CustomField>
    <fullName>Event_Source__c</fullName>
    <description>Source of event</description>
    <label>Event Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OneJN_Event_Log__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>event type</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OneJN_Event_Log__c/fields/Salesforce_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Record_Id__c</fullName>
    <description>Salesforce Record Id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Salesforce Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OneJNErrorReportingController.cls
/**
 * @description       : Controller for the OneJNErrorReporting lightning component
 * @author            : Ishwari Gaikwad(Thinqloud)
 * @group             :
 * @last modified on  : 07-06-2021
 * @last modified by  : Ishwari Gaikwad(Thinqloud)
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   07-06-2021   Ishwari Gaikwad(Thinqloud)   Initial Version
 **/
public class OneJNErrorReportingController {
  /**
   * @description : get the map of error logs for the opportunity and application object
   * @author Ishwari Gaikwad(Thinqloud) | 07-06-2021
   * @param recordId
   * @return Map<Id, Map<String, String>>
   **/
  @AuraEnabled
  public static Map<Id, Map<String, String>> getErrorLogs(Id recordId) {
    Schema.SObjectType objectName = recordId.getSobjectType();

    sObject sobjectRecord = getsObjectRecord(recordId, objectName);
    User userDetails = getUserDetails(
      String.valueOf(sobjectRecord.get('LastModifiedById'))
    );
    Map<Id, Map<String, String>> eventLogMap = new Map<Id, Map<String, String>>();

    List<OneJN_Event_Log__c> eventLogList = getErrorEventLogs(recordId);

    if (!eventLogList.isEmpty() && eventLogList.size() > 0) {
      for (OneJN_Event_Log__c eventLog : eventLogList) {
        String body = eventLog.Body__c;
        Map<String, Object> JSONData = (Map<String, Object>) JSON.deserializeUntyped(
          body
        );
        Map<String, String> valuesMap = new Map<String, String>();
        for (String jsonKey : JSONData.KeySet()) {
          if (JSONData.get(jsonKey) != null || JSONData.get(jsonKey) != '') {
            if (jsonKey == 'SourceEvent') {
              valuesMap.put(
                jsonKey,
                String.valueOf(JSONData.get(jsonKey)).substringAfterLast('.')
              );
            } else {
              valuesMap.put(jsonKey, String.valueOf(JSONData.get(jsonKey)));
            }
          }
        }
        valuesMap.put('Time', eventLog.CreatedDate.format('h:mm a'));
        valuesMap.put('Date', eventLog.CreatedDate.format('MM/dd/yyyy'));
        valuesMap.put('LastModifiedBy', userDetails.Name);
        eventLogMap.put(eventLog.Id, valuesMap);
      }
    }
    return eventLogMap;
  }

  /**
   * @description : get the user details by passing the Id
   * @author Ishwari Gaikwad(Thinqloud) | 07-06-2021
   * @param userId
   * @return User
   **/
  public static User getUserDetails(Id userId) {
    User userDetails = [SELECT ID, Name FROM User WHERE Id = :userId];
    return userDetails;
  }

  /**
   * @description : get the list of error reporting event
   * @author Ishwari Gaikwad(Thinqloud) | 07-06-2021
   * @param recordId
   * @return List<OneJN_Event_Log__c>
   **/
  public static List<OneJN_Event_Log__c> getErrorEventLogs(Id recordId) {
    List<OneJN_Event_Log__c> eventLogList = [
      SELECT Body__c, Id, CreatedDate
      FROM OneJN_Event_Log__c
      WHERE
        Event_Source__c = :Constants.EXTERNAL
        AND Name__c = :Constants.GENERIC_ERROR_EVENT
        AND Salesforce_Record_Id__c = :recordId
      ORDER BY CreatedDate DESC
      LIMIT 5
    ];
    return eventLogList;
  }

  /**
   * @description : get the sobject ( opportunity or Application) record by passing id
   * @author Ishwari Gaikwad(Thinqloud) | 07-06-2021
   * @param recordId
   * @param objectName
   * @return sObject
   **/
  public static sObject getsObjectRecord(
    String recordId,
    Schema.SObjectType objectName
  ) {
    String query =
      'SELECT Id, Name,' +
      ' LastModifiedBy.Name' +
      ' FROM ' +
      objectName +
      ' WHERE Id = \'' +
      recordId +
      '\'';
    sObject sobjectRecord = Database.query(query);
    return sobjectRecord;
  }
}