mdapi/objects/Supplementary_Card_Holders__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Supplementary Card Holder Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Supplementary Card Holder</relationshipLabel>
        <relationshipName>Supplementary_Card_Holder</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Card_Holder_Name__c</fullName>
        <formula>Account__r.FirstName &amp; &apos; &apos; &amp; Account__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Card Holder Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplementary Card Holder</relationshipLabel>
        <relationshipName>Supplementary_Card_Holder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Supplementary Card Holder</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>Supplementary Card Holder&apos;s Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplementary Card Holder</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SupplementaryCardHolderWrapper.cls
/**
 * Ver  Ticket#      Date            Author                  Purpose
 * 1.0  JN1-3969     4/12/2020      Ishwari G.(thinqloud)   Wrapper for Supplementary Card Holder
 **/
public with sharing class SupplementaryCardHolderWrapper {
  @AuraEnabled
  public String cardHolderName;
  @AuraEnabled
  public Id opportunityId;
  @AuraEnabled
  public Id accountId;
  @AuraEnabled
  public String currencyCode;
  @AuraEnabled
  public String supplementaryCardHolderName;
  public SupplementaryCardHolderWrapper(Supplementary_Card_Holders__c record) {
    this.accountId = record.Account__c;
    this.opportunityId = record.Opportunity__c;
    this.cardHolderName = record.Card_Holder_Name__c;
    this.currencyCode = record.CurrencyIsoCode;
    this.supplementaryCardHolderName = record.Name;
  }
}