force-app/main/default/objects/Loan_Calculation_Product__c/Loan_Calculation_Product__c.object-meta.xml
<CustomObject>
    <description
  >Auto, Unsecured, Credit card, and Line of credit products for loan calculation.</description>
    <label>Loan Calculation Product</label>
    <nameField>
        <displayFormat>LCP-{000000}</displayFormat>
        <label>Loan Calculation Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculation Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Ability_to_Service_After_Number__c.field-meta.xml
<CustomField>
    <fullName>Ability_to_Service_After_Number__c</fullName>
    <description>Ability to Service After(TDSR)</description>
    <label>Ability to Service After</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Ability_to_Service_Before_Number__c.field-meta.xml
<CustomField>
    <fullName>Ability_to_Service_Before_Number__c</fullName>
    <description>Ability to Service Before (TDSR)</description>
    <label>Ability to Service Before</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Applicable_Processing_Fee_Number__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Processing_Fee_Number__c</fullName>
    <description>Indicate applicable process fee percent</description>
    <label>Applicable Processing Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Creditor_Life_Insurance_Premium_Number__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Life_Insurance_Premium_Number__c</fullName>
    <description>JN Life Creditor Life Insurance Premium</description>
    <label>JN Life Creditor Life Insurance Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Desired_Monthly_Repayment_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Monthly_Repayment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Desired Monthly Repayment Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/JN_Life_Creditor_Life_Premium_Number__c.field-meta.xml
<CustomField>
    <fullName>JN_Life_Creditor_Life_Premium_Number__c</fullName>
    <label>JN Life Creditor Life Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Legal_Fees_including_GCT_Number__c.field-meta.xml
<CustomField>
    <fullName>Legal_Fees_including_GCT_Number__c</fullName>
    <description>Legal Fees(including GCT)</description>
    <label>Legal Fees(including GCT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_Amount_Market_Percentage_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_Market_Percentage_Number__c</fullName>
    <description>Loan Amount Market Percentage</description>
    <label>Loan Amount Market Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_Calculation_Id__c.field-meta.xml
<CustomField>
    <fullName>Loan_Calculation_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan calculation</description>
    <label>Loan Calculation</label>
    <referenceTo>Loan_Calculator__c</referenceTo>
    <relationshipLabel>Loan Calculation Products</relationshipLabel>
    <relationshipName>Loan_Calculation_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Monthly_Compulsory_Savings_Number__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Compulsory_Savings_Number__c</fullName>
    <label>Monthly Compulsory Savings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Monthly_Creditor_Life_Premium_Number__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Creditor_Life_Premium_Number__c</fullName>
    <description>Monthly Creditor Life Premium as per Credit Limit</description>
    <label>Monthly Creditor Life Premium per Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Monthly_P_I_Life_Insurance_Premium__c.field-meta.xml
<CustomField>
    <fullName>Monthly_P_I_Life_Insurance_Premium__c</fullName>
    <description>Monthly P&amp;I (Life Insurance Premium)</description>
    <label>Monthly P&amp;I (Life Insurance Premium)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Monthly_PI_Loan_Amount_Number__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PI_Loan_Amount_Number__c</fullName>
    <label>Monthly P&amp;I Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Monthly_PI_Processing_Fee_Number__c.field-meta.xml
<CustomField>
    <fullName>Monthly_PI_Processing_Fee_Number__c</fullName>
    <label>Monthly P&amp;I Processing Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Months_Number__c.field-meta.xml
<CustomField>
    <fullName>Months_Number__c</fullName>
    <label>Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Policy_Limit_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Limit_Number__c</fullName>
    <description>Policy Limit</description>
    <label>Policy Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Processing_Fees_Closing_Cost_GCT_Number__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fees_Closing_Cost_GCT_Number__c</fullName>
    <description>Processing Fees Closing Cost(including GCT)</description>
    <label>Processing Fees Closing Cost(GCT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Processing_Fees_including_GCT_Number__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fees_including_GCT_Number__c</fullName>
    <label>Processing Fees (including GCT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Proposed_Savings_Number__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Savings_Number__c</fullName>
    <label>Proposed Savings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Proposed_Savings_Percentage_Number__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Savings_Percentage_Number__c</fullName>
    <label>Proposed Savings Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Repayment_Method_List__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Method_List__c</fullName>
    <description>Repayment Method</description>
    <label>Repayment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salary Deduction</fullName>
            </value>
            <value>
                <fullName>Standing Order</fullName>
            </value>
            <value>
                <fullName>Over The Counter</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Dividends</fullName>
            </value>
            <value>
                <fullName>Alimony</fullName>
            </value>
            <value>
                <fullName>Remittances</fullName>
            </value>
            <value>
                <fullName>Rental Income</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Compulsory_Savings_Balance_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Compulsory_Savings_Balance_Number__c</fullName>
    <description
  >Total Compulsory Savings Balance(Over Repayment Period)</description>
    <label>Total Compulsory Savings Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Interest_Payment_Repayment_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Payment_Repayment_Number__c</fullName>
    <description>Total Interest Payment(Over Repayment Period)</description>
    <label>Total Interest Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Loan_Amount_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Amount_Number__c</fullName>
    <description>Total Loan amount</description>
    <label>Total Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Monthly_Loan_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Loan_Payment_Number__c</fullName>
    <description>Total Monthly Loan Payment</description>
    <label>Total Monthly Loan Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Monthly_PI_Loan_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_PI_Loan_Payment_Number__c</fullName>
    <description>Total Monthly P&amp;I Loan Payment</description>
    <label>Total Monthly P&amp;I Loan Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Monthly_Saving_Loan_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Saving_Loan_Payment_Number__c</fullName>
    <description>Total Monthly Loan Payment + Monthly Loan Savings</description>
    <label>Total Monthly Saving Loan Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Years_Number__c.field-meta.xml
<CustomField>
    <fullName>Years_Number__c</fullName>
    <label>Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <description>Auto loan product</description>
    <label>Auto</label>
</RecordType>

force-app/main/default/objects/Loan_Calculation_Product__c/recordTypes/Credit_Card.recordType-meta.xml
<RecordType>
    <fullName>Credit_Card</fullName>
    <active>true</active>
    <description>Credit card product</description>
    <label>Credit Card</label>
</RecordType>

force-app/main/default/objects/Loan_Calculation_Product__c/recordTypes/Line_of_Credit.recordType-meta.xml
<RecordType>
    <fullName>Line_of_Credit</fullName>
    <active>true</active>
    <description>Line of Credit product</description>
    <label>Line of Credit</label>
</RecordType>

force-app/main/default/objects/Loan_Calculation_Product__c/recordTypes/Unsecured.recordType-meta.xml
<RecordType>
    <fullName>Unsecured</fullName>
    <active>true</active>
    <description>Unsecured product</description>
    <label>Unsecured</label>
</RecordType>

force-app/main/default/classes/LoanCalculationProductUnwrapper.cls
public class LoanCalculationProductUnwrapper {
  private static final String TAG = 'LoanCalculationUnwrapper';
  @AuraEnabled
  public Loan_Calculation_Product__c record;
  public LoanCalculationProductUnwrapper(
    ProductDetailsSerializer serializer,
    List<String> recordTypes
  ) {
    this.record = new Loan_Calculation_Product__c();
    this.record.recordTypeId = assignRecordType(recordTypes);
    record.Years_Number__c = serializer.years;
    record.Months_Number__c = serializer.months;
    record.Loan_Amount_Market_Percentage_Number__c = serializer.market;
    record.Applicable_Processing_Fee_Number__c = serializer.processingFeePercentagePerAnum;
    record.Repayment_Method_List__c = serializer.repaymentMethod;
    record.Desired_Monthly_Repayment_Date__c = serializer.repaymentDate;
    record.Proposed_Savings_Number__c = serializer.proposedSavingsAmount;
    record.Proposed_Savings_Percentage_Number__c = serializer.proposedSavingsPercentage;
    record.Processing_Fees_including_GCT_Number__c = serializer.processingFeesGCT;
    record.Monthly_PI_Processing_Fee_Number__c = serializer.monthlyPrincipalInterestProcessingFee;
    record.Legal_Fees_including_GCT_Number__c = serializer.legalFee;
    record.Processing_Fees_Closing_Cost_GCT_Number__c = serializer.processingFeeClosingCost;
    record.JN_Life_Creditor_Life_Premium_Number__c = serializer.jnLifeCreditorPremium;
    record.Monthly_Compulsory_Savings_Number__c = serializer.monthlyCompulsorySavings;
    record.Total_Compulsory_Savings_Balance_Number__c = serializer.totalCompulsorySavingsBalance;
    record.Monthly_Creditor_Life_Premium_Number__c = serializer.monthlyJnLifeCreditor_PI_Premium;
    record.Total_Loan_Amount_Number__c = serializer.totalLoanAmount;
    record.Total_Monthly_Loan_Payment_Number__c = serializer.totalMonthlyLoanPayment;
    record.Total_Monthly_PI_Loan_Payment_Number__c = serializer.totalMonthly_PI_LoanPayment;
    record.Total_Interest_Payment_Repayment_Number__c = serializer.totalInterestPaymentBalance;
    record.Total_Monthly_Saving_Loan_Payment_Number__c = serializer.totalMonthlyLoanPaymentAndSavings;
    record.Monthly_P_I_Life_Insurance_Premium__c = serializer.monthlyJnLifeCreditor_PI_Premium;
    record.Ability_to_Service_After_Number__c = serializer.TDSRAfter;
    record.Ability_to_Service_Before_Number__c = serializer.TDSRBefore;
    record.Policy_Limit_Number__c = serializer.policyLimit;
    record.Monthly_PI_Loan_Amount_Number__c = serializer.monthly_PI_LoanAmount;
    record.Creditor_Life_Insurance_Premium_Number__c = serializer.jnCLPremiumFeesAndCharges;
  }
  /**
   * save loan calculation product object
   * @param {Id} loanCalculationId
   * @return {Id}
   */
  public Id save(Id loanCalculationId) {
    try {
      this.record.Loan_Calculation_Id__c = loanCalculationId;
      insert this.record;
      return this.record.Id;
    } catch (Exception e) {
      System.debug(TAG + ' ' + e.getMessage());
      throw new StringException(e.getMessage());
    }
  }
  /** *
   * assigns record type
   * @param {List<String>} recordTypes
   * @return {Id} recordTypeId
   */
  private Id assignRecordType(List<String> recordTypes) {
    Map<String, Id> recordTypeIds = Util.getRecordTypeids(
      'Loan_Calculation_Product__c'
    );
    Id recordTypeId;
    if (recordTypes != null) {
      for (String recordType : recordTypes) {
        if (recordType == Constants.AUTO_PRODUCT_FAMILY) {
          recordTypeId = recordTypeIds.get('Auto');
        } else if (recordType == Constants.LINEOFCREDIT_PRODUCT_FAMILY) {
          recordTypeId = recordTypeIds.get('Line_of_Credit');
        } else if (recordType == Constants.CREDITCARD_PRODUCT_FAMILY) {
          recordTypeId = recordTypeIds.get('Credit_Card');
        } else if (recordType == Constants.UNSECURED_PRODUCT_FAMILY) {
          recordTypeId = recordTypeIds.get('Unsecured');
        }
      }
    }
    return recordTypeId;
  }
}