force-app/main/default/objects/Loan_Calculation_Product__c/Loan_Calculation_Product__c.object-meta.xml
<CustomObject>
    <description
  >Auto, Unsecured, Credit card, and Line of credit products for loan calculation.</description>
    <label>Loan Calculation Product</label>
    <nameField>
        <displayFormat>LCP-{000000}</displayFormat>
        <label>Loan Calculation Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculation Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Assignment_Fee_Number__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Fee_Number__c</fullName>
    <description>Assignment Fee</description>
    <label>Assignment Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Months_Number__c.field-meta.xml
<CustomField>
    <fullName>Months_Number__c</fullName>
    <label>Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Years_Number__c.field-meta.xml
<CustomField>
    <fullName>Years_Number__c</fullName>
    <label>Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoanCalculationProductWrapper.cls
public class LoanCalculationProductWrapper {
  /**
   * Story #: JN1-4001
   */
  @AuraEnabled
  public Decimal loanAmount;
  @AuraEnabled
  public Decimal startingLimit;
  @AuraEnabled
  public Decimal assignmentFee;
  @AuraEnabled
  public Decimal years;
  @AuraEnabled
  public Decimal months;
  public LoanCalculationProductWrapper(Loan_Calculation_Product__c record) {
    this.loanAmount = record.Loan_Amount__c;
    this.startingLimit = record.Starting_Limit__c;
    this.assignmentFee = record.Assignment_Fee_Number__c;
    this.years = record.Years_Number__c;
    this.months = record.Months_Number__c;
  }
}