force-app/main/default/objects/Loan_Calculation_Product__c/Loan_Calculation_Product__c.object-meta.xml
<CustomObject>
    <description
  >Auto, Unsecured, Credit card, and Line of credit products for loan calculation.</description>
    <label>Loan Calculation Product</label>
    <nameField>
        <displayFormat>LCP-{000000}</displayFormat>
        <label>Loan Calculation Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculation Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Applicable_Processing_Fee_Number__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Processing_Fee_Number__c</fullName>
    <description>Indicate applicable process fee percent</description>
    <label>Applicable Processing Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Coverage_Type_List__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type_List__c</fullName>
    <description>Coverage Type</description>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Suitable Applicants</fullName>
            </value>
            <value>
                <fullName>Applicant 1 Only</fullName>
            </value>
            <value>
                <fullName>Applicant 2 Only</fullName>
            </value>
            <value>
                <fullName>Applicant 3 Only</fullName>
            </value>
            <value>
                <fullName>Applicant 1 &amp; Applicant 2</fullName>
            </value>
            <value>
                <fullName>Applicant 1 &amp; Applicant 3</fullName>
            </value>
            <value>
                <fullName>Applicant 2 &amp; Applicant 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Desired_Monthly_Repayment_Date__c.field-meta.xml
<CustomField>
    <fullName>Desired_Monthly_Repayment_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Desired Monthly Repayment Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Include_in_Loan_Amount_Flag__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Loan_Amount_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Loan Amount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Include_in_Loan_Amount_Processing_Flag__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Loan_Amount_Processing_Flag__c</fullName>
    <label>Include in Loan Amount (Processing Fee)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No, Paid by Applicant</fullName>
            </value>
            <value>
                <fullName>Yes, Add to Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Interest_Rate_Number__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Number__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Interested_in_Creditor_Life_Flag__c.field-meta.xml
<CustomField>
    <fullName>Interested_in_Creditor_Life_Flag__c</fullName>
    <label>Interested in Creditor Life</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Interested_in_JNGI_SureCover_flag__c.field-meta.xml
<CustomField>
    <fullName>Interested_in_JNGI_SureCover_flag__c</fullName>
    <label>Interested in JNGI SureCover Programme?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/JN_Life_Creditor_Life_Premium_Number__c.field-meta.xml
<CustomField>
    <fullName>JN_Life_Creditor_Life_Premium_Number__c</fullName>
    <label>JN Life Creditor Life Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/JNGI_Motor_Premium_1st_Year_during_Numbe__c.field-meta.xml
<CustomField>
    <fullName>JNGI_Motor_Premium_1st_Year_during_Numbe__c</fullName>
    <label>JNGI Motor Premium (1st Year) during</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_Amount_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_Number__c</fullName>
    <description>Loan Amount for product</description>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_Calculation_Id__c.field-meta.xml
<CustomField>
    <fullName>Loan_Calculation_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan calculation</description>
    <label>Loan Calculation</label>
    <referenceTo>Loan_Calculator__c</referenceTo>
    <relationshipLabel>Loan Calculation Products</relationshipLabel>
    <relationshipName>Loan_Calculation_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Loan_Purpose_List__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose_List__c</fullName>
    <description>Loan Purpose</description>
    <label>Loan Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset Acquisition</fullName>
            </value>
            <value>
                <fullName>Auto Repairs</fullName>
            </value>
            <value>
                <fullName>Debt Consolidation</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Medical Expenses</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Purchase a Motor Vehicle</fullName>
            </value>
            <value>
                <fullName>Refinance existing Auto Loan</fullName>
            </value>
            <value>
                <fullName>Equity in a Motor Vehicle</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
            <value>
                <fullName>Emergency Expenses</fullName>
            </value>
            <value>
                <fullName>Purchase of Appliances</fullName>
            </value>
            <value>
                <fullName>Vehicle Financing</fullName>
            </value>
            <value>
                <fullName>Wedding Expenses</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Make_and_Model_of_Motor_Vehicle_text__c.field-meta.xml
<CustomField>
    <fullName>Make_and_Model_of_Motor_Vehicle_text__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Make and Model of Motor Vehicle</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Market_Value_of_Vehicle_Number__c.field-meta.xml
<CustomField>
    <fullName>Market_Value_of_Vehicle_Number__c</fullName>
    <label>Market Value of Vehicle</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Monthly_Compulsory_Savings_Number__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Compulsory_Savings_Number__c</fullName>
    <label>Monthly Compulsory Savings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Processing_Fees_including_GCT_Number__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fees_including_GCT_Number__c</fullName>
    <label>Processing Fees (including GCT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Purchase_Price_of_Vehicle_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price_of_Vehicle_Number__c</fullName>
    <label>Purchase Price of Vehicle</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Repayment_Method_List__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Method_List__c</fullName>
    <description>Repayment Method</description>
    <label>Repayment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salary Deduction</fullName>
            </value>
            <value>
                <fullName>Standing Order</fullName>
            </value>
            <value>
                <fullName>Over The Counter</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Dividends</fullName>
            </value>
            <value>
                <fullName>Alimony</fullName>
            </value>
            <value>
                <fullName>Remittances</fullName>
            </value>
            <value>
                <fullName>Rental Income</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Closing_Costs_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Closing_Costs_Number__c</fullName>
    <description>Total Closing Costs</description>
    <label>Total Closing Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Total_Monthly_Saving_Loan_Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Saving_Loan_Payment_Number__c</fullName>
    <description>Total Monthly Loan Payment + Monthly Loan Savings</description>
    <label>Total Monthly Saving Loan Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Year_of_Motor_Vehicle_Number__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Motor_Vehicle_Number__c</fullName>
    <label>Year of Motor Vehicle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/fields/Years_Number__c.field-meta.xml
<CustomField>
    <fullName>Years_Number__c</fullName>
    <label>Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Calculation_Product__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <description>Auto loan product</description>
    <label>Auto</label>
</RecordType>

mdapipkg/Scratch/objects/Loan_Calculator__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Loan_Purpose__c</fullName>
        <label>Auto Loan Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Purchase a Motor Vehicle</fullName>
                </value>
                <value>
                    <fullName>Refinance existing Auto Loan</fullName>
                </value>
                <value>
                    <fullName>Equity in a Motor Vehicle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Desired_Monthly_Repayment_Date__c</fullName>
        <label>Desired Monthly Repayment Date</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PCL_Requested_Credit_Limit__c</fullName>
        <label>PCL Requested Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PC_Credit_Limit_Amount__c</fullName>
        <label>PC Credit Limit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>unsecure_Loan_Purpose__c</fullName>
        <label>Unsecure Loan Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Asset Acquisition</fullName>
                </value>
                <value>
                    <fullName>Auto Repairs</fullName>
                </value>
                <value>
                    <fullName>Debt Consolidation</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Home Improvement</fullName>
                </value>
                <value>
                    <fullName>Medical Expenses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan Calculation</label>
    <nameField>
        <displayFormat>LC-{000000000}</displayFormat>
        <label>Loan Calculator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Calculations</pluralLabel>
    <recordTypes>
        <fullName>Product_Details</fullName>
        <active>true</active>
        <label>Product Details</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Calculator__c/fields/Total_Closing_Costs_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Closing_Costs_Number__c</fullName>
    <label>Total Closing Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapipkg/Scratch/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Desired_Monthly_Repayment_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Desired Monthly Repayment Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/classes/PromissoryNoteController_Test.cls
@isTest
public class PromissoryNoteController_Test {
  @isTest
  public static void testPdf() {
    List<Opportunity> opList = TestDataFactory.CreateOpportunities(1);
    List<Account> accList = TestDataFactory.CreateBasicAccounts(1, 'Test');
    accList[0].Years_at_Residence__pc = 4;
    accList[0]
      .Highest_Level_of_Education_attained__pc = 'University: Post Graduate';
    accList[0].PersonBirthdate = date.newInstance(
      System.Today().year() - 36,
      2,
      11
    );
    insert accList;

    Util.ExecutionCount = 2;
    Map<String, Id> recordTypeMap2 = Util.getRecordTypeids(
      'Loan_Calculator__c'
    );
    List<Loan_Calculator__c> loanCalcList = TestDataFactory.CreateLoanCalculation(
      1
    );
    loanCalcList[0].RecordTypeId = recordTypeMap2.get('Product_Details');
    loanCalcList[0].Auto_Loan_Purpose__c = 'Purchase a Motor Vehicle';
    loanCalcList[0].unsecure_Loan_Purpose__c = 'Asset Acquisition';
    loanCalcList[0].PC_Credit_Limit_Amount__c = 2000.00;
    loanCalcList[0].PCL_Requested_Credit_Limit__c = 300.00;
    insert loanCalcList;

    List<Loan_Calculation_Product__c> loanCalcProductList = TestDataFactory.CreateLoanCalculationProduct(
      1
    );
    loanCalcProductList[0].Loan_Calculation_Id__c = loanCalcList[0].Id;
    loanCalcProductList[0].Loan_Amount_Number__c = 20000.00;
    loanCalcProductList[0].Years_Number__c = 2;
    loanCalcProductList[0].Loan_Purpose_List__c = 'Purchase a Motor Vehicle';
    loanCalcProductList[0].Interest_Rate_Number__c = 3;
    loanCalcProductList[0]
      .Total_Monthly_Saving_Loan_Payment_Number__c = 20000.00;
    loanCalcProductList[0].Monthly_Compulsory_Savings_Number__c = 2000.00;
    loanCalcProductList[0].Applicable_Processing_Fee_Number__c = 3000.00;
    loanCalcProductList[0].Processing_Fees_including_GCT_Number__c = 3000.00;
    loanCalcProductList[0]
      .Include_in_Loan_Amount_Processing_Flag__c = 'No, Paid by Applicant';
    loanCalcProductList[0].Interested_in_Creditor_Life_Flag__c = 'Yes';
    loanCalcProductList[0]
      .Include_in_Loan_Amount_Flag__c = 'No, Paid by Applicant';
    loanCalcProductList[0].JN_Life_Creditor_Life_Premium_Number__c = 3000.00;
    loanCalcProductList[0].Coverage_Type_List__c = 'Applicant 1 Only';
    loanCalcProductList[0].Total_Closing_Costs_Number__c = 3000.00;
    loanCalcProductList[0].Repayment_Method_List__c = 'Salary Deduction';
    loanCalcProductList[0].Desired_Monthly_Repayment_Date__c = '12';
    loanCalcProductList[0].Year_of_Motor_Vehicle_Number__c = 2019;
    loanCalcProductList[0].Make_and_Model_of_Motor_Vehicle_text__c = 'test 222';
    loanCalcProductList[0].Market_Value_of_Vehicle_Number__c = 20000.00;
    loanCalcProductList[0].Purchase_Price_of_Vehicle_Number__c = 20000.00;
    loanCalcProductList[0].Interested_in_JNGI_SureCover_flag__c = 'Yes';
    loanCalcProductList[0].JNGI_Motor_Premium_1st_Year_during_Numbe__c = 2000;
    loanCalcProductList[0]
      .Include_in_Loan_Amount_JNGI_list__c = 'No, Paid by Applicant';
    loanCalcProductList[0].Vehicle_Classification_list__c = 'New';
    loanCalcProductList[0].Months_Number__c = 7;
    loanCalcProductList[0].Collateral_Type_List__c = 'Cash/Investments';
    loanCalcProductList[0].Desired_Statement_Date__c = date.newInstance(
      System.Today().year(),
      2,
      11
    );
    loanCalcProductList[0].Financial_Institution_List__c = 'JN Bank Ltd.';
    loanCalcProductList[0].Annual_Interest_Rate_Deposit_Acct_Number__c = 2;
    loanCalcProductList[0].Account_Holder_s_text__c = 'test';
    loanCalcProductList[0].Deposit_Account_Balance_Number__c = 2000.00;
    loanCalcProductList[0].Account_Hypothecated_list__c = 'Yes';
    loanCalcProductList[0].Existing_Loan_Balance_Number__c = 2000.00;
    loanCalcProductList[0].Requested_Credit_Limit_Number__c = 2000.00;
    loanCalcProductList[0].Annual_Creditor_Life_Fee_Number__c = 2000.00;
    loanCalcProductList[0].Annual_Membership_Primary_Number__c = 2000.00;
    loanCalcProductList[0].Annual_Membership_Supplementary_Number__c = 2000.00;
    insert loanCalcProductList;

    opList[0].accountId = accList[0].id;
    opList[0].Collateral_CC__c = 'Cash';
    opList[0].Collateral_LOC__c = 'Cash';
    opList[0].Loan_to_ValueCC__c = 1;
    opList[0].StageName = 'Customer Interview';
    opList[0].CloseDate = Date.today().addDays(6);
    opList[0].Product_Details__c = loanCalcList[0].Id;
    insert opList[0];

    List<Product2> products = new List<Product2>();
    List<String> families = new List<String>{ 'JN Bank Auto Loan' };
    for (String family : families) {
      //add each product to be created
      products.add(
        TestDataFactory.CreateProduct(family, 'iPhone X - ' + family)
      );
    }
    //Insert products with families
    insert products;

    //Instantiate the Pricebook2 record with StandardPricebookId
    Pricebook2 standardPricebook = new Pricebook2(
      Id = Test.getStandardPricebookId(),
      IsActive = true
    );

    //Execute an update DML on the Pricebook2 recordapplicant.to make IsStandard to true
    //update standardPricebook;

    //Query for the Pricebook2 recordapplicant.to check IsStandard field
    /*standardPricebook = [
            SELECT Id, IsStandard
            FROM Pricebook2
            WHERE Id = :standardPricebook.Id
            FOR UPDATE
        ];
        //It should return true
        System.assertEquals(true, standardPricebook.IsStandard);*/

    List<PricebookEntry> priceBookEntries = new List<PricebookEntry>();
    for (Product2 record : products) {
      priceBookEntries.add(
        TestDataFactory.CreatePriceBookEntry(standardPricebook.Id, record.Id)
      );
    }
    //Insert Price Book Entries
    insert priceBookEntries;

    List<OpportunityLineItem> lineItems = new List<OpportunityLineItem>();
    for (PricebookEntry record : priceBookEntries) {
      lineItems.add(
        TestDataFactory.CreateOpportunityLineItem(opList[0].id, record.Id)
      );
    }
    // Insert Opportunity Line Items
    insert lineItems;
    Test.StartTest();
    pageReference pageRef = page.PromissoryNotePage;
    pageRef.getParameters().put('Id', String.valueOf(opList[0].Id));
    Test.setCurrentPage(pageRef);
    PromissoryNoteController pnc = new PromissoryNoteController();
    Test.StopTest();
  }
}